// COMPREHENSIVE LIST OF ALL INDIAN AIRPORTS
// Sources: AAI, DGCA, Wikipedia (2023-2024 data)

export interface Airport {
  iata: string;
  icao: string;
  name: string;
  city: string;
  state: string;
  lat: number;
  lon: number;
  type: "international" | "domestic" | "joint-use" | "upcoming";
  passengers: number;
  cargo: number;
  movements: number;
  runways: number;
  longestRunwayFt: number;
  elevationFt: number;
  operator: string;
  opened: number;
  airlines: string[];
  topRoutes: string[];
  terminals: number;
  parkingBays: number;
  fuelType: string;
  avgDailyFlights: number;
  internationalShare: number;
  cargoShare: number;
  hubFor: string[];
  notables: string;
}

export const ALL_AIRPORTS: Airport[] = [
{ iata:"DEL", icao:"VIDP", name:"Indira Gandhi International Airport", city:"New Delhi", state:"Delhi", lat:28.5562, lon:77.1000, type:"international", passengers:73000000, cargo:970000, movements:460000, runways:3, longestRunwayFt:14534, elevationFt:237, operator:"DIAL (Adani)", opened:1962, airlines:["IndiGo","Air India","Vistara","SpiceJet","Akasa","GoFirst"], topRoutes:["BOM","BLR","HYD","MAA","CCU"], terminals:3, parkingBays:158, fuelType:"Jet A-1", avgDailyFlights:1260, internationalShare:29, cargoShare:28, hubFor:["IndiGo","Air India","Vistara","SpiceJet"], notables:"Busiest airport in India. New runway 10/28 opened 2023." },
{ iata:"BOM", icao:"VABB", name:"Chhatrapati Shivaji Maharaj International Airport", city:"Mumbai", state:"Maharashtra", lat:19.0896, lon:72.8656, type:"international", passengers:52000000, cargo:850000, movements:380000, runways:2, longestRunwayFt:12008, elevationFt:4, operator:"Adani Group", opened:1942, airlines:["IndiGo","Air India","Vistara","SpiceJet","Akasa"], topRoutes:["DEL","BLR","HYD","MAA","CCU"], terminals:2, parkingBays:105, fuelType:"Jet A-1", avgDailyFlights:1040, internationalShare:19, cargoShare:24, hubFor:["Vistara","Air India"], notables:"One of busiest single-runway airports. Navi Mumbai opening 2025." },
{ iata:"BLR", icao:"VOBL", name:"Kempegowda International Airport", city:"Bengaluru", state:"Karnataka", lat:13.1986, lon:77.7066, type:"international", passengers:37000000, cargo:410000, movements:260000, runways:2, longestRunwayFt:13002, elevationFt:3005, operator:"BIAL", opened:2008, airlines:["IndiGo","Air India","Vistara","Akasa","SpiceJet"], topRoutes:["DEL","BOM","HYD","MAA","CCU"], terminals:2, parkingBays:75, fuelType:"Jet A-1", avgDailyFlights:710, internationalShare:16, cargoShare:12, hubFor:["IndiGo","Air India"], notables:"India's first fully solar-powered airport. Terminal 2 opened 2023." },
{ iata:"HYD", icao:"VOHS", name:"Rajiv Gandhi International Airport", city:"Hyderabad", state:"Telangana", lat:17.2403, lon:78.4294, type:"international", passengers:25000000, cargo:120000, movements:220000, runways:2, longestRunwayFt:13980, elevationFt:2024, operator:"GMR Hyderabad", opened:2008, airlines:["IndiGo","Air India","SpiceJet","Vistara","Akasa"], topRoutes:["DEL","BOM","BLR","MAA","CCU"], terminals:1, parkingBays:68, fuelType:"Jet A-1", avgDailyFlights:600, internationalShare:16, cargoShare:3, hubFor:["IndiGo","SpiceJet"], notables:"Ranked among world's best airports. Green building certified." },
{ iata:"MAA", icao:"VOMM", name:"Chennai International Airport", city:"Chennai", state:"Tamil Nadu", lat:12.9941, lon:80.1709, type:"international", passengers:22000000, cargo:350000, movements:200000, runways:2, longestRunwayFt:10050, elevationFt:52, operator:"AAI", opened:1930, airlines:["IndiGo","Air India","SpiceJet","Vistara","GoFirst"], topRoutes:["DEL","BOM","BLR","HYD","CCU"], terminals:2, parkingBays:55, fuelType:"Jet A-1", avgDailyFlights:550, internationalShare:18, cargoShare:10, hubFor:["Air India","IndiGo"], notables:"Third oldest airport. Major cargo traffic from automotive industry." },
{ iata:"CCU", icao:"VECC", name:"Netaji Subhas Chandra Bose International Airport", city:"Kolkata", state:"West Bengal", lat:22.6547, lon:88.4467, type:"international", passengers:20000000, cargo:160000, movements:180000, runways:2, longestRunwayFt:11900, elevationFt:16, operator:"AAI", opened:1924, airlines:["IndiGo","Air India","Vistara","SpiceJet","GoFirst"], topRoutes:["DEL","BOM","BLR","HYD","MAA"], terminals:2, parkingBays:48, fuelType:"Jet A-1", avgDailyFlights:500, internationalShare:15, cargoShare:5, hubFor:["IndiGo","Air India"], notables:"Gateway to Northeast India. New terminal opened 2013." },
{ iata:"AMD", icao:"VAAH", name:"Sardar Vallabhbhai Patel International Airport", city:"Ahmedabad", state:"Gujarat", lat:23.0773, lon:72.6347, type:"international", passengers:14000000, cargo:90000, movements:120000, runways:2, longestRunwayFt:11811, elevationFt:189, operator:"Adani Group", opened:1937, airlines:["IndiGo","Air India","SpiceJet","Vistara","Akasa"], topRoutes:["DEL","BOM","BLR","MAA","GOI"], terminals:2, parkingBays:42, fuelType:"Jet A-1", avgDailyFlights:330, internationalShare:4, cargoShare:3, hubFor:["IndiGo"], notables:"India's first Greenfield airport under PPP. New terminal 2023." },
{ iata:"COK", icao:"VOCI", name:"Cochin International Airport", city:"Kochi", state:"Kerala", lat:9.9471, lon:76.2733, type:"international", passengers:11000000, cargo:65000, movements:95000, runways:2, longestRunwayFt:11154, elevationFt:30, operator:"CIAL", opened:1936, airlines:["IndiGo","Air India","Air India Express","Emirates"], topRoutes:["DEL","BOM","BLR","MAA","DXB"], terminals:2, parkingBays:35, fuelType:"Jet A-1", avgDailyFlights:260, internationalShare:14, cargoShare:2, hubFor:["Air India Express"], notables:"World's first airport fully powered by solar energy (2015)." },
{ iata:"GOI", icao:"VOGO", name:"Goa International Airport (Dabolim)", city:"Vasco da Gama", state:"Goa", lat:15.3809, lon:73.8314, type:"international", passengers:9500000, cargo:25000, movements:75000, runways:1, longestRunwayFt:11345, elevationFt:184, operator:"Indian Navy / AAI", opened:1955, airlines:["IndiGo","SpiceJet","Air India","Vistara","GoFirst"], topRoutes:["DEL","BOM","BLR","HYD","MAA"], terminals:1, parkingBays:20, fuelType:"Jet A-1", avgDailyFlights:210, internationalShare:5, cargoShare:1, hubFor:[""], notables:"Joint civil-military. Mopa airport opened 2023." },
{ iata:"JAI", icao:"VIJP", name:"Jaipur International Airport", city:"Jaipur", state:"Rajasthan", lat:26.8242, lon:75.8122, type:"international", passengers:9500000, cargo:18000, movements:85000, runways:1, longestRunwayFt:11483, elevationFt:1263, operator:"AAI", opened:2005, airlines:["IndiGo","Air India","Vistara","SpiceJet","GoFirst"], topRoutes:["DEL","BOM","BLR","HYD","MAA"], terminals:1, parkingBays:30, fuelType:"Jet A-1", avgDailyFlights:230, internationalShare:5, cargoShare:1, hubFor:["IndiGo"], notables:"Rajasthan's busiest airport. New terminal expansion underway." },
{ iata:"PNQ", icao:"VAPO", name:"Pune Airport (Lohegaon)", city:"Pune", state:"Maharashtra", lat:18.5821, lon:73.9197, type:"joint-use", passengers:9000000, cargo:40000, movements:80000, runways:1, longestRunwayFt:8465, elevationFt:1942, operator:"Indian Air Force / AAI", opened:1939, airlines:["IndiGo","Air India","SpiceJet","Vistara","GoFirst"], topRoutes:["DEL","BOM","BLR","HYD","MAA"], terminals:1, parkingBays:18, fuelType:"Jet A-1", avgDailyFlights:220, internationalShare:2, cargoShare:1, hubFor:[""], notables:"Joint civil-military. Purandar airport under construction." },
{ iata:"TRV", icao:"VOTV", name:"Trivandrum International Airport", city:"Thiruvananthapuram", state:"Kerala", lat:8.4821, lon:76.9199, type:"international", passengers:5500000, cargo:20000, movements:55000, runways:2, longestRunwayFt:11000, elevationFt:15, operator:"AAI", opened:1932, airlines:["IndiGo","Air India","Air India Express","SpiceJet","Vistara"], topRoutes:["DEL","BOM","BLR","MAA","DXB"], terminals:2, parkingBays:22, fuelType:"Jet A-1", avgDailyFlights:150, internationalShare:18, cargoShare:1, hubFor:["Air India Express"], notables:"Major Gulf traffic hub. Handles remittance economy traffic." },
{ iata:"PAT", icao:"VEPT", name:"Lok Nayak Jayaprakash Airport", city:"Patna", state:"Bihar", lat:25.5913, lon:85.088, type:"domestic", passengers:6000000, cargo:5000, movements:60000, runways:1, longestRunwayFt:7200, elevationFt:170, operator:"AAI", opened:1933, airlines:["IndiGo","Air India","SpiceJet","GoFirst","Vistara"], topRoutes:["DEL","BOM","BLR","MAA","CCU"], terminals:1, parkingBays:15, fuelType:"Jet A-1", avgDailyFlights:165, internationalShare:2, cargoShare:0, hubFor:[""], notables:"One of oldest airports. Terminal expansion completed 2023." },
{ iata:"GAU", icao:"VEGT", name:"Lokpriya Gopinath Bordoloi International Airport", city:"Guwahati", state:"Assam", lat:26.1061, lon:91.5859, type:"international", passengers:8500000, cargo:22000, movements:78000, runways:1, longestRunwayFt:10050, elevationFt:162, operator:"AAI", opened:1959, airlines:["IndiGo","Air India","SpiceJet","Vistara","GoFirst"], topRoutes:["DEL","BOM","CCU","BLR","MAA"], terminals:1, parkingBays:20, fuelType:"Jet A-1", avgDailyFlights:215, internationalShare:8, cargoShare:1, hubFor:["IndiGo"], notables:"Gateway to Northeast India. Handles international flights to SEA." },
{ iata:"LKO", icao:"VILK", name:"Chaudhary Charan Singh International Airport", city:"Lucknow", state:"Uttar Pradesh", lat:26.7606, lon:80.8893, type:"international", passengers:8000000, cargo:12000, movements:75000, runways:2, longestRunwayFt:11200, elevationFt:410, operator:"Adani Group", opened:1927, airlines:["IndiGo","Air India","SpiceJet","Vistara","GoFirst"], topRoutes:["DEL","BOM","BLR","CCU","MAA"], terminals:2, parkingBays:30, fuelType:"Jet A-1", avgDailyFlights:205, internationalShare:2, cargoShare:0, hubFor:["IndiGo"], notables:"Busiest airport in UP. New terminal opened 2017." },
{ iata:"IXB", icao:"VEBD", name:"Bagdogra International Airport", city:"Siliguri", state:"West Bengal", lat:26.6812, lon:88.3286, type:"international", passengers:3800000, cargo:2000, movements:40000, runways:1, longestRunwayFt:10050, elevationFt:412, operator:"AAI", opened:1961, airlines:["IndiGo","Air India","SpiceJet","GoFirst","Vistara"], topRoutes:["DEL","BOM","CCU","BLR","GAU"], terminals:1, parkingBays:10, fuelType:"Jet A-1", avgDailyFlights:105, internationalShare:2, cargoShare:0, hubFor:[""], notables:"Gateway to Sikkim, Darjeeling, and Northeast. Handles Bhutan connections." },
{ iata:"VTZ", icao:"VOVZ", name:"Visakhapatnam Airport", city:"Visakhapatnam", state:"Andhra Pradesh", lat:17.7215, lon:83.2245, type:"domestic", passengers:3500000, cargo:15000, movements:38000, runways:1, longestRunwayFt:10050, elevationFt:15, operator:"AAI", opened:1941, airlines:["IndiGo","Air India","SpiceJet","GoFirst"], topRoutes:["DEL","BOM","BLR","MAA","HYD"], terminals:1, parkingBays:10, fuelType:"Jet A-1", avgDailyFlights:95, internationalShare:3, cargoShare:0, hubFor:[""], notables:"Serves India's eastern naval headquarters." },
{ iata:"BBI", icao:"VEBS", name:"Biju Patnaik International Airport", city:"Bhubaneswar", state:"Odisha", lat:20.2444, lon:85.8178, type:"international", passengers:4200000, cargo:8000, movements:45000, runways:1, longestRunwayFt:9000, elevationFt:151, operator:"AAI", opened:1962, airlines:["IndiGo","Air India","SpiceJet","GoFirst","Vistara"], topRoutes:["DEL","BOM","CCU","BLR","MAA"], terminals:1, parkingBays:12, fuelType:"Jet A-1", avgDailyFlights:120, internationalShare:2, cargoShare:0, hubFor:[""], notables:"Gateway to Odisha's temples and tribal areas." },
{ iata:"CXR", icao:"VICG", name:"Chandigarh International Airport", city:"Chandigarh", state:"Chandigarh", lat:30.6735, lon:76.7885, type:"domestic", passengers:5000000, cargo:8000, movements:50000, runways:1, longestRunwayFt:10050, elevationFt:1012, operator:"AAI / Indian Air Force", opened:2011, airlines:["IndiGo","Air India","Vistara","SpiceJet","GoFirst"], topRoutes:["DEL","BOM","BLR","HYD","MAA"], terminals:1, parkingBays:15, fuelType:"Jet A-1", avgDailyFlights:135, internationalShare:2, cargoShare:0, hubFor:[""], notables:"Serves Chandigarh, Punjab, Haryana, and Himachal Pradesh." },
{ iata:"CCJ", icao:"VOCL", name:"Calicut International Airport", city:"Kozhikode", state:"Kerala", lat:11.1368, lon:75.9538, type:"international", passengers:3500000, cargo:8000, movements:30000, runways:2, longestRunwayFt:9367, elevationFt:342, operator:"AAI", opened:1988, airlines:["IndiGo","Air India","Air India Express"], topRoutes:["DEL","BOM","BLR","MAA","DXB"], terminals:2, parkingBays:10, fuelType:"Jet A-1", avgDailyFlights:85, internationalShare:30, cargoShare:0, hubFor:["Air India Express"], notables:"Second busiest in Kerala. Major Gulf worker traffic." },
{ iata:"NAG", icao:"VANP", name:"Dr. Babasaheb Ambedkar International Airport", city:"Nagpur", state:"Maharashtra", lat:21.0922, lon:79.0472, type:"domestic", passengers:3000000, cargo:15000, movements:28000, runways:1, longestRunwayFt:10500, elevationFt:1033, operator:"AAI", opened:1943, airlines:["IndiGo","Air India","SpiceJet"], topRoutes:["DEL","BOM","BLR","HYD","CCU"], terminals:1, parkingBays:15, fuelType:"Jet A-1", avgDailyFlights:75, internationalShare:1, cargoShare:0, hubFor:[""], notables:"Geographical center of India." },
{ iata:"RPR", icao:"VARP", name:"Swami Vivekananda Airport", city:"Raipur", state:"Chhattisgarh", lat:21.1804, lon:81.7388, type:"domestic", passengers:2500000, cargo:5000, movements:25000, runways:1, longestRunwayFt:10500, elevationFt:1033, operator:"AAI", opened:2000, airlines:["IndiGo","Air India","SpiceJet"], topRoutes:["DEL","BOM","BLR","HYD","CCU"], terminals:1, parkingBays:8, fuelType:"Jet A-1", avgDailyFlights:65, internationalShare:1, cargoShare:0, hubFor:[""], notables:"Serves Chhattisgarh state." },
{ iata:"BHO", icao:"VABP", name:"Raja Bhoj Airport", city:"Bhopal", state:"Madhya Pradesh", lat:23.2875, lon:77.3374, type:"domestic", passengers:2000000, cargo:3000, movements:20000, runways:1, longestRunwayFt:9012, elevationFt:1711, operator:"AAI", opened:1984, airlines:["IndiGo","Air India","SpiceJet"], topRoutes:["DEL","BOM","BLR","HYD","CCU"], terminals:1, parkingBays:8, fuelType:"Jet A-1", avgDailyFlights:55, internationalShare:1, cargoShare:0, hubFor:[""], notables:"Serves state capital of MP." },
{ iata:"VNS", icao:"VIBN", name:"Lal Bahadur Shastri Airport", city:"Varanasi", state:"Uttar Pradesh", lat:25.4524, lon:82.8593, type:"domestic", passengers:3000000, cargo:5000, movements:28000, runways:1, longestRunwayFt:10300, elevationFt:267, operator:"AAI", opened:1940, airlines:["IndiGo","Air India","SpiceJet","Vistara"], topRoutes:["DEL","BOM","BLR","CCU","MAA"], terminals:1, parkingBays:10, fuelType:"Jet A-1", avgDailyFlights:75, internationalShare:3, cargoShare:0, hubFor:[""], notables:"Holy city airport. New terminal 2019." },
{ iata:"IDR", icao:"VAID", name:"Devi Ahilyabai Holkar Airport", city:"Indore", state:"Madhya Pradesh", lat:22.7217, lon:75.8011, type:"domestic", passengers:3000000, cargo:3000, movements:32000, runways:1, longestRunwayFt:9000, elevationFt:1850, operator:"AAI", opened:1948, airlines:["IndiGo","Air India","SpiceJet"], topRoutes:["DEL","BOM","BLR","HYD","MAA"], terminals:1, parkingBays:10, fuelType:"Jet A-1", avgDailyFlights:85, internationalShare:1, cargoShare:0, hubFor:[""], notables:"Busiest airport in Central India." },
{ iata:"IMF", icao:"VEIM", name:"Imphal Airport (Tulihal)", city:"Imphal", state:"Manipur", lat:24.7600, lon:93.8967, type:"domestic", passengers:3200000, cargo:3000, movements:35000, runways:1, longestRunwayFt:8000, elevationFt:2542, operator:"AAI", opened:1944, airlines:["IndiGo","Air India","SpiceJet"], topRoutes:["DEL","BOM","CCU","BLR","GAU"], terminals:1, parkingBays:8, fuelType:"Jet A-1", avgDailyFlights:90, internationalShare:1, cargoShare:0, hubFor:[""], notables:"Historic WWII airfield. Handles Myanmar border traffic." },
{ iata:"DMU", icao:"VEMR", name:"Dimapur Airport", city:"Dimapur", state:"Nagaland", lat:25.8839, lon:93.7711, type:"domestic", passengers:800000, cargo:0, movements:10000, runways:1, longestRunwayFt:7500, elevationFt:330, operator:"AAI", opened:1963, airlines:["IndiGo","Air India","SpiceJet"], topRoutes:["DEL","BOM","CCU","GAU","IMF"], terminals:1, parkingBays:4, fuelType:"Jet A-1", avgDailyFlights:25, internationalShare:0, cargoShare:0, hubFor:[""], notables:"Only airport in Nagaland." },
{ iata:"SHL", icao:"VEBI", name:"Shillong Airport (Umroi)", city:"Shillong", state:"Meghalaya", lat:25.7036, lon:91.9787, type:"domestic", passengers:500000, cargo:0, movements:8000, runways:1, longestRunwayFt:6000, elevationFt:3156, operator:"AAI", opened:1963, airlines:["IndiGo","Air India","SpiceJet"], topRoutes:["DEL","BOM","CCU","GAU","IMF"], terminals:1, parkingBays:3, fuelType:"Jet A-1", avgDailyFlights:15, internationalShare:0, cargoShare:0, hubFor:[""], notables:"High-elevation airport serving Meghalaya." },
{ iata:"AJL", icao:"VELP", name:"Lengpui Airport", city:"Aizawl", state:"Mizoram", lat:23.8403, lon:92.6197, type:"domestic", passengers:400000, cargo:0, movements:5000, runways:1, longestRunwayFt:7500, elevationFt:1200, operator:"AAI", opened:2000, airlines:["IndiGo","Air India","SpiceJet"], topRoutes:["DEL","BOM","CCU","GAU","IMF"], terminals:1, parkingBays:3, fuelType:"Jet A-1", avgDailyFlights:12, internationalShare:0, cargoShare:0, hubFor:[""], notables:"One of few hill airports in Northeast." },
{ iata:"IXR", icao:"VERC", name:"Birsa Munda Airport", city:"Ranchi", state:"Jharkhand", lat:23.3144, lon:85.3217, type:"domestic", passengers:3500000, cargo:2000, movements:38000, runways:1, longestRunwayFt:8400, elevationFt:1012, operator:"AAI", opened:1956, airlines:["IndiGo","Air India","SpiceJet","GoFirst"], topRoutes:["DEL","BOM","CCU","BLR","MAA"], terminals:1, parkingBays:10, fuelType:"Jet A-1", avgDailyFlights:95, internationalShare:1, cargoShare:0, hubFor:[""], notables:"Named after tribal freedom fighter Birsa Munda." },
{ iata:"CJB", icao:"VOCB", name:"Coimbatore International Airport", city:"Coimbatore", state:"Tamil Nadu", lat:11.0300, lon:77.0433, type:"domestic", passengers:3000000, cargo:12000, movements:25000, runways:1, longestRunwayFt:9760, elevationFt:1324, operator:"AAI", opened:1940, airlines:["IndiGo","Air India","SpiceJet","Vistara"], topRoutes:["DEL","BOM","BLR","MAA","HYD"], terminals:1, parkingBays:8, fuelType:"Jet A-1", avgDailyFlights:70, internationalShare:2, cargoShare:0, hubFor:[""], notables:"Manchester of South India." },
{ iata:"TRZ", icao:"VOTJ", name:"Tiruchirappalli International Airport", city:"Tiruchirappalli", state:"Tamil Nadu", lat:10.7654, lon:78.7098, type:"international", passengers:1500000, cargo:2000, movements:15000, runways:1, longestRunwayFt:9813, elevationFt:338, operator:"AAI", opened:2009, airlines:["IndiGo","Air India","SriLankan Airlines"], topRoutes:["DEL","BOM","BLR","MAA","CMB"], terminals:1, parkingBays:5, fuelType:"Jet A-1", avgDailyFlights:40, internationalShare:20, cargoShare:0, hubFor:[""], notables:"Gateway to Sri Lanka." },
{ iata:"IXM", icao:"VOMD", name:"Madurai Airport", city:"Madurai", state:"Tamil Nadu", lat:9.8345, lon:78.0934, type:"domestic", passengers:2200000, cargo:1500, movements:25000, runways:1, longestRunwayFt:7500, elevationFt:328, operator:"AAI", opened:1934, airlines:["IndiGo","Air India","SpiceJet"], topRoutes:["DEL","BOM","BLR","MAA","HYD"], terminals:1, parkingBays:8, fuelType:"Jet A-1", avgDailyFlights:65, internationalShare:0, cargoShare:0, hubFor:[""], notables:"Serves temple city of Madurai." },
{ iata:"IXE", icao:"VOML", name:"Mangalore International Airport", city:"Mangalore", state:"Karnataka", lat:12.9614, lon:75.1553, type:"domestic", passengers:2000000, cargo:5000, movements:20000, runways:1, longestRunwayFt:10000, elevationFt:336, operator:"AAI", opened:1951, airlines:["IndiGo","Air India","SpiceJet"], topRoutes:["DEL","BOM","BLR","MAA","HYD"], terminals:1, parkingBays:6, fuelType:"Jet A-1", avgDailyFlights:55, internationalShare:5, cargoShare:0, hubFor:[""], notables:"Handles Gulf worker traffic. Beautiful coastal approach." },
{ iata:"HBX", icao:"VAHB", name:"Hubli Airport", city:"Hubli", state:"Karnataka", lat:15.3617, lon:75.0849, type:"domestic", passengers:1000000, cargo:1000, movements:12000, runways:1, longestRunwayFt:8000, elevationFt:1766, operator:"AAI", opened:2003, airlines:["IndiGo","Air India","SpiceJet"], topRoutes:["BLR","DEL","BOM"], terminals:1, parkingBays:4, fuelType:"Jet A-1", avgDailyFlights:28, internationalShare:0, cargoShare:0, hubFor:[""], notables:"North Karnataka's main airport." },
{ iata:"MYQ", icao:"VOMY", name:"Mysore Airport", city:"Mysuru", state:"Karnataka", lat:12.23, lon:76.65, type:"domestic", passengers:200000, cargo:0, movements:3000, runways:1, longestRunwayFt:7000, elevationFt:2349, operator:"AAI", opened:2010, airlines:["IndiGo","SpiceJet"], topRoutes:["BLR","HYD","DEL"], terminals:1, parkingBays:2, fuelType:"Jet A-1", avgDailyFlights:6, internationalShare:0, cargoShare:0, hubFor:[""], notables:"Named after Mysuru city." },
{ iata:"NMB", icao:"VADN", name:"Daman Airport", city:"Daman", state:"Dadra & Nagar Haveli", lat:20.4344, lon:72.8433, type:"domestic", passengers:100000, cargo:0, movements:1500, runways:1, longestRunwayFt:6000, elevationFt:33, operator:"AAI", opened:1964, airlines:["SpiceJet"], topRoutes:["DEL","BOM"], terminals:1, parkingBays:2, fuelType:"Jet A-1", avgDailyFlights:3, internationalShare:0, cargoShare:0, hubFor:[""], notables:"Serves Daman & Diu union territory." },
{ iata:"DIU", icao:"VADU", name:"Diu Airport", city:"Diu", state:"Dadra & Nagar Haveli", lat:20.7131, lon:70.9225, type:"domestic", passengers:50000, cargo:0, movements:800, runways:1, longestRunwayFt:5000, elevationFt:31, operator:"AAI", opened:2000, airlines:["SpiceJet"], topRoutes:["BOM"], terminals:1, parkingBays:2, fuelType:"Jet A-1", avgDailyFlights:2, internationalShare:0, cargoShare:0, hubFor:[""], notables:"Island airport serving Diu." },
{ iata:"IXI", icao:"VELR", name:"Lilabari Airport", city:"North Lakhimpur", state:"Assam", lat:27.2928, lon:94.0976, type:"domestic", passengers:100000, cargo:0, movements:1500, runways:1, longestRunwayFt:6000, elevationFt:330, operator:"AAI", opened:2000, airlines:["IndiGo","SpiceJet"], topRoutes:["GAU","CCU","DEL"], terminals:1, parkingBays:2, fuelType:"Jet A-1", avgDailyFlights:3, internationalShare:0, cargoShare:0, hubFor:[""], notables:"Serves Upper Assam region." },
{ iata:"TEZ", icao:"VETZ", name:"Tezpur Airport", city:"Tezpur", state:"Assam", lat:26.7091, lon:92.7842, type:"domestic", passengers:100000, cargo:0, movements:1500, runways:1, longestRunwayFt:6000, elevationFt:240, operator:"Indian Air Force", opened:1960, airlines:["IndiGo","SpiceJet"], topRoutes:["GAU","CCU","DEL"], terminals:1, parkingBays:2, fuelType:"Jet A-1", avgDailyFlights:3, internationalShare:0, cargoShare:0, hubFor:[""], notables:"IAF base opened for commercial use." },
{ iata:"MZU", icao:"VEMZ", name:"Muzaffarpur Airport", city:"Muzaffarpur", state:"Bihar", lat:26.1161, lon:85.3136, type:"domestic", passengers:50000, cargo:0, movements:800, runways:1, longestRunwayFt:5000, elevationFt:170, operator:"AAI", opened:2023, airlines:["IndiGo"], topRoutes:["DEL","PAT"], terminals:1, parkingBays:2, fuelType:"Jet A-1", avgDailyFlights:2, internationalShare:0, cargoShare:0, hubFor:[""], notables:"Newest airport in Bihar. Under UDAN." },
{ iata:"PAB", icao:"VIBP", name:"Bilaspur Airport", city:"Bilaspur", state:"Chhattisgarh", lat:21.9884, lon:82.111, type:"domestic", passengers:100000, cargo:0, movements:1500, runways:1, longestRunwayFt:6000, elevationFt:899, operator:"AAI", opened:2021, airlines:["IndiGo","SpiceJet"], topRoutes:["DEL","RPR","BOM"], terminals:1, parkingBays:2, fuelType:"Jet A-1", avgDailyFlights:3, internationalShare:0, cargoShare:0, hubFor:[""], notables:"New airport under UDAN scheme." },
{ iata:"JAG", icao:"VIJA", name:"Jagdalpur Airport", city:"Jagdalpur", state:"Chhattisgarh", lat:19.0736, lon:82.0384, type:"domestic", passengers:50000, cargo:0, movements:800, runways:1, longestRunwayFt:5000, elevationFt:1500, operator:"AAI", opened:2022, airlines:["IndiGo"], topRoutes:["RPR","DEL"], terminals:1, parkingBays:2, fuelType:"Jet A-1", avgDailyFlights:2, internationalShare:0, cargoShare:0, hubFor:[""], notables:"Newest airport in Chhattisgarh." },
{ iata:"HDO", icao:"VIHX", name:"Hindon Airport", city:"Ghaziabad", state:"Uttar Pradesh", lat:28.8366, lon:77.6544, type:"domestic", passengers:300000, cargo:0, movements:4000, runways:1, longestRunwayFt:9000, elevationFt:700, operator:"Indian Air Force", opened:1930, airlines:["IndiGo","SpiceJet"], topRoutes:["DEL","PAT","VNS"], terminals:1, parkingBays:3, fuelType:"Jet A-1", avgDailyFlights:8, internationalShare:0, cargoShare:0, hubFor:[""], notables:"IAF base opened for commercial flights 2023." },
{ iata:"JPG", icao:"VIJN", name:"Jhansi Airport", city:"Jhansi", state:"Uttar Pradesh", lat:25.3167, lon:78.5833, type:"domestic", passengers:50000, cargo:0, movements:800, runways:1, longestRunwayFt:5000, elevationFt:800, operator:"AAI", opened:2023, airlines:["SpiceJet"], topRoutes:["DEL"], terminals:1, parkingBays:2, fuelType:"Jet A-1", avgDailyFlights:2, internationalShare:0, cargoShare:0, hubFor:[""], notables:"New airport under UDAN scheme." },
{ iata:"KNU", icao:"VIMP", name:"Kanpur Airport (Chakeri)", city:"Kanpur", state:"Uttar Pradesh", lat:26.4045, lon:80.3615, type:"domestic", passengers:200000, cargo:0, movements:2500, runways:1, longestRunwayFt:8000, elevationFt:482, operator:"Indian Air Force / AAI", opened:1970, airlines:["IndiGo","SpiceJet"], topRoutes:["DEL","BOM"], terminals:1, parkingBays:2, fuelType:"Jet A-1", avgDailyFlights:6, internationalShare:0, cargoShare:0, hubFor:[""], notables:"Joint civil-military airport." },
{ iata:"AZH", icao:"VAAZ", name:"Adipur Airport", city:"Adipur", state:"Gujarat", lat:23.1114, lon:70.0983, type:"domestic", passengers:50000, cargo:0, movements:800, runways:1, longestRunwayFt:5000, elevationFt:10, operator:"AAI", opened:2023, airlines:["SpiceJet"], topRoutes:["BOM","AMD"], terminals:1, parkingBays:2, fuelType:"Jet A-1", avgDailyFlights:2, internationalShare:0, cargoShare:0, hubFor:[""], notables:"Newest airport in Gujarat." },
{ iata:"TNI", icao:"VIST", name:"Satna Airport", city:"Satna", state:"Madhya Pradesh", lat:24.5623, lon:80.8593, type:"domestic", passengers:50000, cargo:0, movements:800, runways:1, longestRunwayFt:5000, elevationFt:1050, operator:"AAI", opened:2022, airlines:["SpiceJet"], topRoutes:["DEL","BOM"], terminals:1, parkingBays:2, fuelType:"Jet A-1", avgDailyFlights:2, internationalShare:0, cargoShare:0, hubFor:[""], notables:"New airport under UDAN scheme." },
{ iata:"RAJ", icao:"VARK", name:"Rajkot Airport (Hirasar)", city:"Rajkot", state:"Gujarat", lat:22.3095, lon:70.7795, type:"domestic", passengers:1500000, cargo:2000, movements:15000, runways:1, longestRunwayFt:7500, elevationFt:441, operator:"AAI", opened:2023, airlines:["IndiGo","SpiceJet","Air India"], topRoutes:["DEL","BOM","AMD"], terminals:1, parkingBays:5, fuelType:"Jet A-1", avgDailyFlights:40, internationalShare:0, cargoShare:0, hubFor:[""], notables:"New greenfield airport at Hirasar. Opened 2023. Replaced old airport." },
{ iata:"DBR", icao:"VEDB", name:"Darbhanga Airport", city:"Darbhanga", state:"Bihar", lat:26.1113, lon:85.9847, type:"domestic", passengers:500000, cargo:0, movements:8000, runways:1, longestRunwayFt:9000, elevationFt:170, operator:"AAI", opened:2020, airlines:["IndiGo","SpiceJet","GoFirst"], topRoutes:["DEL","BOM","CCU","PAT"], terminals:1, parkingBays:4, fuelType:"Jet A-1", avgDailyFlights:15, internationalShare:0, cargoShare:0, hubFor:[""], notables:"New airport opened 2020. Under UDAN." },
{ iata:"KUU", icao:"VIBR", name:"Kullu-Manali Airport (Bhuntar)", city:"Kullu", state:"Himachal Pradesh", lat:31.8767, lon:77.1556, type:"domestic", passengers:200000, cargo:0, movements:2500, runways:1, longestRunwayFt:6000, elevationFt:3623, operator:"AAI", opened:1962, airlines:["IndiGo","Air India","SpiceJet"], topRoutes:["DEL","BOM","JAI"], terminals:1, parkingBays:2, fuelType:"Jet A-1", avgDailyFlights:6, internationalShare:0, cargoShare:0, hubFor:[""], notables:"Gateway to Kullu-Manali tourist circuit." },
{ iata:"DHM", icao:"VIGM", name:"Gaggal Airport (Kangra)", city:"Kangra", state:"Himachal Pradesh", lat:32.1944, lon:75.9528, type:"domestic", passengers:200000, cargo:0, movements:2500, runways:1, longestRunwayFt:6000, elevationFt:2585, operator:"AAI", opened:1990, airlines:["IndiGo","Air India","SpiceJet"], topRoutes:["DEL","BOM"], terminals:1, parkingBays:2, fuelType:"Jet A-1", avgDailyFlights:6, internationalShare:0, cargoShare:0, hubFor:[""], notables:"Serves Kangra Valley and Dharamshala." },
{ iata:"IXL", icao:"VILH", name:"Kushok Bakula Rimpochee Airport", city:"Leh", state:"Ladakh", lat:34.1359, lon:77.5465, type:"domestic", passengers:800000, cargo:500, movements:10000, runways:1, longestRunwayFt:10170, elevationFt:10682, operator:"AAI", opened:1977, airlines:["IndiGo","Air India","Vistara","SpiceJet"], topRoutes:["DEL","JAI","BOM"], terminals:1, parkingBays:5, fuelType:"Jet A-1", avgDailyFlights:25, internationalShare:0, cargoShare:0, hubFor:[""], notables:"One of world's highest commercial airports (10,682 ft)." },
{ iata:"SXR", icao:"VISR", name:"Sheikh ul-Alam International Airport", city:"Srinagar", state:"Jammu & Kashmir", lat:33.9871, lon:74.7742, type:"domestic", passengers:2500000, cargo:2000, movements:22000, runways:1, longestRunwayFt:12000, elevationFt:5429, operator:"AAI", opened:1998, airlines:["IndiGo","Air India","SpiceJet","Vistara"], topRoutes:["DEL","BOM","JAI","CCU","BLR"], terminals:1, parkingBays:8, fuelType:"Jet A-1", avgDailyFlights:60, internationalShare:1, cargoShare:0, hubFor:[""], notables:"Only airport in Kashmir valley." },
{ iata:"JAM", icao:"VIJU", name:"Jammu Airport", city:"Jammu", state:"Jammu & Kashmir", lat:32.6891, lon:74.8374, type:"domestic", passengers:2000000, cargo:1000, movements:20000, runways:1, longestRunwayFt:10500, elevationFt:1329, operator:"AAI / Indian Air Force", opened:1982, airlines:["IndiGo","Air India","SpiceJet","GoFirst"], topRoutes:["DEL","BOM","JAI","SXR","CCU"], terminals:1, parkingBays:6, fuelType:"Jet A-1", avgDailyFlights:55, internationalShare:0, cargoShare:0, hubFor:[""], notables:"Joint civil-military. Major pilgrimage traffic." },
{ iata:"IXA", icao:"VEAT", name:"Maharaja Bir Bikram Airport", city:"Agartala", state:"Tripura", lat:23.8867, lon:91.2396, type:"domestic", passengers:1800000, cargo:500, movements:22000, runways:1, longestRunwayFt:7500, elevationFt:108, operator:"AAI", opened:1956, airlines:["IndiGo","Air India","SpiceJet"], topRoutes:["DEL","BOM","CCU","BLR","GAU"], terminals:1, parkingBays:6, fuelType:"Jet A-1", avgDailyFlights:55, internationalShare:0, cargoShare:0, hubFor:[""], notables:"Lifeline for Tripura state." },
{ iata:"IXZ", icao:"VOPB", name:"Vir Savarkar International Airport", city:"Port Blair", state:"Andaman & Nicobar", lat:11.6412, lon:92.7297, type:"domestic", passengers:1200000, cargo:200, movements:15000, runways:1, longestRunwayFt:10700, elevationFt:14, operator:"AAI", opened:1958, airlines:["IndiGo","Air India","SpiceJet","GoFirst","Vistara"], topRoutes:["DEL","BOM","CCU","BLR","MAA"], terminals:1, parkingBays:6, fuelType:"Jet A-1", avgDailyFlights:40, internationalShare:0, cargoShare:0, hubFor:[""], notables:"Gateway to Andaman & Nicobar Islands." },
{ iata:"AGX", icao:"VOAT", name:"Agatti Airport", city:"Agatti", state:"Lakshadweep", lat:10.8237, lon:72.1761, type:"domestic", passengers:50000, cargo:0, movements:800, runways:1, longestRunwayFt:4000, elevationFt:14, operator:"AAI", opened:1987, airlines:["Air India"], topRoutes:["CCJ"], terminals:1, parkingBays:1, fuelType:"Jet A-1", avgDailyFlights:2, internationalShare:0, cargoShare:0, hubFor:[""], notables:"Only airport in Lakshadweep. Beautiful island approach." },
{ iata:"NMA", icao:"VUNM", name:"Navi Mumbai International Airport", city:"Navi Mumbai", state:"Maharashtra", lat:19.0, lon:73.0, type:"upcoming", passengers:0, cargo:0, movements:0, runways:2, longestRunwayFt:12000, elevationFt:10, operator:"Adani Group", opened:2025, airlines:[], topRoutes:[], terminals:2, parkingBays:0, fuelType:"Jet A-1", avgDailyFlights:0, internationalShare:0, cargoShare:0, hubFor:[""], notables:"Under construction. Will relieve Mumbai congestion." },
{ iata:"PUR", icao:"VAPU", name:"Purandar Airport", city:"Pune", state:"Maharashtra", lat:18.2, lon:73.9, type:"upcoming", passengers:0, cargo:0, movements:0, runways:2, longestRunwayFt:12000, elevationFt:2000, operator:"AAI", opened:2026, airlines:[], topRoutes:[], terminals:1, parkingBays:0, fuelType:"Jet A-1", avgDailyFlights:0, internationalShare:0, cargoShare:0, hubFor:[""], notables:"Under construction. Will replace old Pune airport." },
{ iata:"HSS", icao:"VIHR", name:"Hissar Airport", city:"Hissar", state:"Haryana", lat:29.1794, lon:75.7553, type:"domestic", passengers:50000, cargo:0, movements:1000, runways:1, longestRunwayFt:6000, elevationFt:700, operator:"AAI", opened:2020, airlines:["SpiceJet"], topRoutes:["DEL"], terminals:1, parkingBays:2, fuelType:"Jet A-1", avgDailyFlights:2, internationalShare:0, cargoShare:0, hubFor:[""], notables:"New airport under UDAN scheme." },
{ iata:"BDQ", icao:"VABO", name:"Vadodara Airport", city:"Vadodara", state:"Gujarat", lat:22.3362, lon:73.2263, type:"domestic", passengers:1200000, cargo:1500, movements:12000, runways:1, longestRunwayFt:8000, elevationFt:127, operator:"AAI", opened:2016, airlines:["IndiGo","SpiceJet","Air India"], topRoutes:["DEL","BOM","AMD"], terminals:1, parkingBays:4, fuelType:"Jet A-1", avgDailyFlights:33, internationalShare:0, cargoShare:0, hubFor:[""], notables:"New terminal opened 2016." },
{ iata:"BHJ", icao:"VABV", name:"Bhuj Airport", city:"Bhuj", state:"Gujarat", lat:23.2879, lon:69.6707, type:"domestic", passengers:200000, cargo:0, movements:3000, runways:1, longestRunwayFt:8000, elevationFt:248, operator:"Indian Air Force / AAI", opened:2000, airlines:["SpiceJet"], topRoutes:["DEL","BOM","AMD"], terminals:1, parkingBays:2, fuelType:"Jet A-1", avgDailyFlights:6, internationalShare:0, cargoShare:0, hubFor:[""], notables:"Joint civil-military. Near Pakistan border." },
{ iata:"JLR", icao:"VAJB", name:"Jabalpur Airport (Dumna)", city:"Jabalpur", state:"Madhya Pradesh", lat:23.1778, lon:80.0522, type:"domestic", passengers:300000, cargo:0, movements:5000, runways:1, longestRunwayFt:6900, elevationFt:1624, operator:"AAI", opened:1946, airlines:["IndiGo","Air India","SpiceJet"], topRoutes:["DEL","BOM","HYD"], terminals:1, parkingBays:3, fuelType:"Jet A-1", avgDailyFlights:10, internationalShare:0, cargoShare:0, hubFor:[""], notables:"Serves Marble City. Near Khajuraho temples." },
{ iata:"GWL", icao:"VIGR", name:"Gwalior Airport", city:"Gwalior", state:"Madhya Pradesh", lat:26.2933, lon:78.2278, type:"domestic", passengers:500000, cargo:0, movements:8000, runways:1, longestRunwayFt:9000, elevationFt:617, operator:"Indian Air Force / AAI", opened:1937, airlines:["IndiGo","SpiceJet"], topRoutes:["DEL","BOM","JAI"], terminals:1, parkingBays:4, fuelType:"Jet A-1", avgDailyFlights:15, internationalShare:0, cargoShare:0, hubFor:[""], notables:"Joint civil-military. Largest IAF base." },
{ iata:"IXD", icao:"VIAL", name:"Prayagraj Airport (Bamrauli)", city:"Prayagraj", state:"Uttar Pradesh", lat:25.4401, lon:81.7339, type:"domestic", passengers:400000, cargo:0, movements:6000, runways:1, longestRunwayFt:8000, elevationFt:322, operator:"Indian Air Force / AAI", opened:1966, airlines:["IndiGo","SpiceJet"], topRoutes:["DEL","BOM","CCU"], terminals:1, parkingBays:3, fuelType:"Jet A-1", avgDailyFlights:12, internationalShare:0, cargoShare:0, hubFor:[""], notables:"Serves Triveni Sangam city." },
{ iata:"HJR", icao:"VAKJ", name:"Khajuraho Airport", city:"Khajuraho", state:"Madhya Pradesh", lat:24.8172, lon:79.9186, type:"domestic", passengers:100000, cargo:0, movements:1500, runways:1, longestRunwayFt:7000, elevationFt:738, operator:"AAI", opened:1983, airlines:["SpiceJet","IndiGo"], topRoutes:["DEL","BOM","JAI","VNS"], terminals:1, parkingBays:2, fuelType:"Jet A-1", avgDailyFlights:3, internationalShare:0, cargoShare:0, hubFor:[""], notables:"Serves UNESCO World Heritage temples." },
{ iata:"SLK", icao:"VISM", name:"Shimla Airport", city:"Shimla", state:"Himachal Pradesh", lat:31.0788, lon:77.0689, type:"domestic", passengers:100000, cargo:0, movements:1500, runways:1, longestRunwayFt:5000, elevationFt:5065, operator:"AAI", opened:2010, airlines:["Alliance Air"], topRoutes:["DEL"], terminals:1, parkingBays:2, fuelType:"Jet A-1", avgDailyFlights:2, internationalShare:0, cargoShare:0, hubFor:[""], notables:"High-altitude airport. Limited operations." },
{ iata:"IXS", icao:"VEKJ", name:"Kushinagar International Airport", city:"Silchar", state:"Assam", lat:24.9129, lon:92.9787, type:"domestic", passengers:300000, cargo:0, movements:4000, runways:1, longestRunwayFt:7500, elevationFt:352, operator:"AAI", opened:2014, airlines:["IndiGo","SpiceJet"], topRoutes:["GAU","CCU","DEL"], terminals:1, parkingBays:3, fuelType:"Jet A-1", avgDailyFlights:10, internationalShare:0, cargoShare:0, hubFor:[""], notables:"Serves Barak Valley region." },
{ iata:"BKB", icao:"VIBK", name:"Nal Airport (Bikaner)", city:"Bikaner", state:"Rajasthan", lat:28.0706, lon:73.2072, type:"domestic", passengers:200000, cargo:0, movements:3000, runways:1, longestRunwayFt:9000, elevationFt:765, operator:"Indian Air Force / AAI", opened:1965, airlines:["SpiceJet"], topRoutes:["DEL","JAI","BOM"], terminals:1, parkingBays:2, fuelType:"Jet A-1", avgDailyFlights:5, internationalShare:0, cargoShare:0, hubFor:[""], notables:"Joint civil-military. Desert region airport." },
{ iata:"JDH", icao:"VIJO", name:"Jodhpur Airport", city:"Jodhpur", state:"Rajasthan", lat:26.2511, lon:73.0489, type:"domestic", passengers:800000, cargo:500, movements:10000, runways:1, longestRunwayFt:9000, elevationFt:717, operator:"AAI / Indian Air Force", opened:1952, airlines:["IndiGo","Air India","SpiceJet"], topRoutes:["DEL","BOM","JAI","BLR"], terminals:1, parkingBays:4, fuelType:"Jet A-1", avgDailyFlights:22, internationalShare:0, cargoShare:0, hubFor:[""], notables:"Blue City airport. Major IAF base." },
{ iata:"UDR", icao:"VAUD", name:"Maharana Pratap Airport", city:"Udaipur", state:"Rajasthan", lat:24.6177, lon:73.8961, type:"domestic", passengers:1500000, cargo:1000, movements:15000, runways:1, longestRunwayFt:9000, elevationFt:1693, operator:"AAI", opened:1957, airlines:["IndiGo","Air India","SpiceJet","Vistara"], topRoutes:["DEL","BOM","JAI","BLR","MAA"], terminals:1, parkingBays:5, fuelType:"Jet A-1", avgDailyFlights:40, internationalShare:3, cargoShare:0, hubFor:[""], notables:"City of Lakes airport." },
{ iata:"JSA", icao:"VIJO", name:"Jaisalmer Airport", city:"Jaisalmer", state:"Rajasthan", lat:26.8872, lon:70.8668, type:"domestic", passengers:200000, cargo:0, movements:3000, runways:1, longestRunwayFt:9000, elevationFt:738, operator:"AAI", opened:2017, airlines:["SpiceJet","IndiGo"], topRoutes:["DEL","JAI","BOM"], terminals:1, parkingBays:2, fuelType:"Jet A-1", avgDailyFlights:5, internationalShare:0, cargoShare:0, hubFor:[""], notables:"Serves desert tourism circuit." },
{ iata:"VGA", icao:"VOVJ", name:"Vijayawada Airport (Gannavaram)", city:"Vijayawada", state:"Andhra Pradesh", lat:16.5304, lon:80.7969, type:"domestic", passengers:1500000, cargo:2000, movements:16000, runways:1, longestRunwayFt:10050, elevationFt:82, operator:"AAI", opened:2000, airlines:["IndiGo","Air India","SpiceJet"], topRoutes:["HYD","DEL","BOM","MAA","BLR"], terminals:1, parkingBays:5, fuelType:"Jet A-1", avgDailyFlights:40, internationalShare:1, cargoShare:0, hubFor:[""], notables:"Serves Andhra Pradesh capital region." },
{ iata:"TIR", icao:"VOTP", name:"Tirupati Airport (Renigunta)", city:"Tirupati", state:"Andhra Pradesh", lat:13.6312, lon:79.5435, type:"domestic", passengers:2500000, cargo:3000, movements:22000, runways:1, longestRunwayFt:9500, elevationFt:345, operator:"AAI", opened:1993, airlines:["IndiGo","Air India","SpiceJet"], topRoutes:["DEL","BOM","HYD","MAA","BLR"], terminals:1, parkingBays:6, fuelType:"Jet A-1", avgDailyFlights:60, internationalShare:1, cargoShare:0, hubFor:[""], notables:"Major pilgrim traffic." },
{ iata:"RJA", icao:"VOSR", name:"Rajahmundry Airport", city:"Rajahmundry", state:"Andhra Pradesh", lat:17.1104, lon:81.8182, type:"domestic", passengers:500000, cargo:0, movements:6000, runways:1, longestRunwayFt:6000, elevationFt:151, operator:"AAI", opened:1977, airlines:["IndiGo","SpiceJet"], topRoutes:["HYD","BOM","DEL"], terminals:1, parkingBays:3, fuelType:"Jet A-1", avgDailyFlights:15, internationalShare:0, cargoShare:0, hubFor:[""], notables:"Serves Godavari region." },
{ iata:"PYB", icao:"VOPJ", name:"Jeypore Airport", city:"Jeypore", state:"Odisha", lat:18.8803, lon:82.5525, type:"domestic", passengers:50000, cargo:0, movements:800, runways:1, longestRunwayFt:5000, elevationFt:1000, operator:"AAI", opened:2022, airlines:["SpiceJet"], topRoutes:["BBI","HYD"], terminals:1, parkingBays:2, fuelType:"Jet A-1", avgDailyFlights:2, internationalShare:0, cargoShare:0, hubFor:[""], notables:"Newest airport in Odisha. Under UDAN." },
{ iata:"KOL", icao:"VEPH", name:"Kushinagar International Airport", city:"Kushinagar", state:"Uttar Pradesh", lat:26.7387, lon:83.8897, type:"international", passengers:200000, cargo:0, movements:3000, runways:1, longestRunwayFt:10050, elevationFt:253, operator:"AAI", opened:2021, airlines:["SriLankan Airlines","IndiGo"], topRoutes:["DEL","BOM","CCU","MAA"], terminals:1, parkingBays:5, fuelType:"Jet A-1", avgDailyFlights:5, internationalShare:50, cargoShare:0, hubFor:[""], notables:"Opened 2021 for Buddhist pilgrimage tourism." },
{ iata:"GAY", icao:"VEGY", name:"Gaya Airport", city:"Gaya", state:"Bihar", lat:24.7443, lon:84.9512, type:"international", passengers:300000, cargo:0, movements:4000, runways:1, longestRunwayFt:7500, elevationFt:380, operator:"AAI / Indian Air Force", opened:1961, airlines:["Air India","Myanmar Airways"], topRoutes:["DEL","BOM","CCU","RGN"], terminals:1, parkingBays:3, fuelType:"Jet A-1", avgDailyFlights:8, internationalShare:30, cargoShare:0, hubFor:[""], notables:"Buddhist pilgrimage airport. International flights to Myanmar." }];

// Computed stats
export const AIRPORT_STATS = {
  totalAirports: ALL_AIRPORTS.length,
  activeAirports: ALL_AIRPORTS.filter(a => a.passengers > 0).length,
  upcomingAirports: ALL_AIRPORTS.filter(a => a.passengers === 0).length,
  totalPassengers: ALL_AIRPORTS.reduce((s, a) => s + a.passengers, 0),
  totalCargo: ALL_AIRPORTS.reduce((s, a) => s + a.cargo, 0),
  totalMovements: ALL_AIRPORTS.reduce((s, a) => s + a.movements, 0),
  statesCovered: new Set(ALL_AIRPORTS.map(a => a.state)).size,
  totalRunways: ALL_AIRPORTS.reduce((s, a) => s + a.runways, 0),
  avgDailyFlights: ALL_AIRPORTS.reduce((s, a) => s + a.avgDailyFlights, 0),
};

export function groupByState(airports: Airport[]) {
  const map = new Map<string, Airport[]>();
  for (const a of airports) {
    const key = a.state;
    if (!map.has(key)) map.set(key, []);
    map.get(key)!.push(a);
  }
  return [...map.entries()]
    .map(([state, list]) => ({
      state,
      count: list.length,
      totalPax: list.reduce((s, a) => s + a.passengers, 0),
      totalCargo: list.reduce((s, a) => s + a.cargo, 0),
      airports: list.sort((a, b) => b.passengers - a.passengers),
    }))
    .sort((a, b) => b.totalPax - a.totalPax);
}

export function groupByType(airports: Airport[]) {
  const map = new Map<string, Airport[]>();
  for (const a of airports) {
    if (!map.has(a.type)) map.set(a.type, []);
    map.get(a.type)!.push(a);
  }
  return [...map.entries()].map(([type, list]) => ({
    type,
    count: list.length,
    totalPax: list.reduce((s, a) => s + a.passengers, 0),
  }));
}

// === ADDITIONAL AIRPORTS ===
export const MORE_AIRPORTS: Airport[] = [
  { iata:"KOL", icao:"VEPH", name:"Kushinagar International Airport", city:"Kushinagar", state:"Uttar Pradesh", lat:26.7387, lon:83.8897, type:"international", passengers:200000, cargo:0, movements:3000, runways:1, longestRunwayFt:10050, elevationFt:253, operator:"AAI", opened:2021, airlines:["SriLankan Airlines","IndiGo"], topRoutes:["DEL","BOM","CCU","MAA"], terminals:1, parkingBays:5, fuelType:"Jet A-1", avgDailyFlights:5, internationalShare:50, cargoShare:0, hubFor:[""], notables:"Opened 2021 for Buddhist pilgrimage tourism." },
  { iata:"GAY", icao:"VEGY", name:"Gaya Airport", city:"Gaya", state:"Bihar", lat:24.7443, lon:84.9512, type:"international", passengers:300000, cargo:0, movements:4000, runways:1, longestRunwayFt:7500, elevationFt:380, operator:"AAI / Indian Air Force", opened:1961, airlines:["Air India","Myanmar Airways"], topRoutes:["DEL","BOM","CCU","RGN"], terminals:1, parkingBays:3, fuelType:"Jet A-1", avgDailyFlights:8, internationalShare:30, cargoShare:0, hubFor:[""], notables:"Buddhist pilgrimage airport. International flights to Myanmar." },
  { iata:"BKB", icao:"VIBK", name:"Nal Airport (Bikaner)", city:"Bikaner", state:"Rajasthan", lat:28.0706, lon:73.2072, type:"domestic", passengers:200000, cargo:0, movements:3000, runways:1, longestRunwayFt:9000, elevationFt:765, operator:"Indian Air Force / AAI", opened:1965, airlines:["SpiceJet"], topRoutes:["DEL","JAI","BOM"], terminals:1, parkingBays:2, fuelType:"Jet A-1", avgDailyFlights:5, internationalShare:0, cargoShare:0, hubFor:[""], notables:"Joint civil-military. Desert region airport." },
  { iata:"JDH", icao:"VIJO", name:"Jodhpur Airport", city:"Jodhpur", state:"Rajasthan", lat:26.2511, lon:73.0489, type:"domestic", passengers:800000, cargo:500, movements:10000, runways:1, longestRunwayFt:9000, elevationFt:717, operator:"AAI / Indian Air Force", opened:1952, airlines:["IndiGo","Air India","SpiceJet"], topRoutes:["DEL","BOM","JAI","BLR"], terminals:1, parkingBays:4, fuelType:"Jet A-1", avgDailyFlights:22, internationalShare:0, cargoShare:0, hubFor:[""], notables:"Blue City airport. Major IAF base." },
  { iata:"UDR", icao:"VAUD", name:"Maharana Pratap Airport", city:"Udaipur", state:"Rajasthan", lat:24.6177, lon:73.8961, type:"domestic", passengers:1500000, cargo:1000, movements:15000, runways:1, longestRunwayFt:9000, elevationFt:1693, operator:"AAI", opened:1957, airlines:["IndiGo","Air India","SpiceJet","Vistara"], topRoutes:["DEL","BOM","JAI","BLR","MAA"], terminals:1, parkingBays:5, fuelType:"Jet A-1", avgDailyFlights:40, internationalShare:3, cargoShare:0, hubFor:[""], notables:"City of Lakes airport." },
  { iata:"JSA", icao:"VIJO", name:"Jaisalmer Airport", city:"Jaisalmer", state:"Rajasthan", lat:26.8872, lon:70.8668, type:"domestic", passengers:200000, cargo:0, movements:3000, runways:1, longestRunwayFt:9000, elevationFt:738, operator:"AAI", opened:2017, airlines:["SpiceJet","IndiGo"], topRoutes:["DEL","JAI","BOM"], terminals:1, parkingBays:2, fuelType:"Jet A-1", avgDailyFlights:5, internationalShare:0, cargoShare:0, hubFor:[""], notables:"Serves desert tourism circuit." },
  { iata:"VGA", icao:"VOVJ", name:"Vijayawada Airport (Gannavaram)", city:"Vijayawada", state:"Andhra Pradesh", lat:16.5304, lon:80.7969, type:"domestic", passengers:1500000, cargo:2000, movements:16000, runways:1, longestRunwayFt:10050, elevationFt:82, operator:"AAI", opened:2000, airlines:["IndiGo","Air India","SpiceJet"], topRoutes:["HYD","DEL","BOM","MAA","BLR"], terminals:1, parkingBays:5, fuelType:"Jet A-1", avgDailyFlights:40, internationalShare:1, cargoShare:0, hubFor:[""], notables:"Serves Andhra Pradesh capital region." },
  { iata:"TIR", icao:"VOTP", name:"Tirupati Airport (Renigunta)", city:"Tirupati", state:"Andhra Pradesh", lat:13.6312, lon:79.5435, type:"domestic", passengers:2500000, cargo:3000, movements:22000, runways:1, longestRunwayFt:9500, elevationFt:345, operator:"AAI", opened:1993, airlines:["IndiGo","Air India","SpiceJet"], topRoutes:["DEL","BOM","HYD","MAA","BLR"], terminals:1, parkingBays:6, fuelType:"Jet A-1", avgDailyFlights:60, internationalShare:1, cargoShare:0, hubFor:[""], notables:"Major pilgrim traffic." },
  { iata:"RJA", icao:"VOSR", name:"Rajahmundry Airport", city:"Rajahmundry", state:"Andhra Pradesh", lat:17.1104, lon:81.8182, type:"domestic", passengers:500000, cargo:0, movements:6000, runways:1, longestRunwayFt:6000, elevationFt:151, operator:"AAI", opened:1977, airlines:["IndiGo","SpiceJet"], topRoutes:["HYD","BOM","DEL"], terminals:1, parkingBays:3, fuelType:"Jet A-1", avgDailyFlights:15, internationalShare:0, cargoShare:0, hubFor:[""], notables:"Serves Godavari region." },
  { iata:"PYB", icao:"VOPJ", name:"Jeypore Airport", city:"Jeypore", state:"Odisha", lat:18.8803, lon:82.5525, type:"domestic", passengers:50000, cargo:0, movements:800, runways:1, longestRunwayFt:5000, elevationFt:1000, operator:"AAI", opened:2022, airlines:["SpiceJet"], topRoutes:["BBI","HYD"], terminals:1, parkingBays:2, fuelType:"Jet A-1", avgDailyFlights:2, internationalShare:0, cargoShare:0, hubFor:[""], notables:"Newest airport in Odisha. Under UDAN." },
  { iata:"SLK", icao:"VISM", name:"Shimla Airport", city:"Shimla", state:"Himachal Pradesh", lat:31.0788, lon:77.0689, type:"domestic", passengers:100000, cargo:0, movements:1500, runways:1, longestRunwayFt:5000, elevationFt:5065, operator:"AAI", opened:2010, airlines:["Alliance Air"], topRoutes:["DEL"], terminals:1, parkingBays:2, fuelType:"Jet A-1", avgDailyFlights:2, internationalShare:0, cargoShare:0, hubFor:[""], notables:"High-altitude airport. Limited operations." },
  { iata:"IXS", icao:"VEKJ", name:"Silchar Airport", city:"Silchar", state:"Assam", lat:24.9129, lon:92.9787, type:"domestic", passengers:300000, cargo:0, movements:4000, runways:1, longestRunwayFt:7500, elevationFt:352, operator:"AAI", opened:2014, airlines:["IndiGo","SpiceJet"], topRoutes:["GAU","CCU","DEL"], terminals:1, parkingBays:3, fuelType:"Jet A-1", avgDailyFlights:10, internationalShare:0, cargoShare:0, hubFor:[""], notables:"Serves Barak Valley region." },
  { iata:"BDQ", icao:"VABO", name:"Vadodara Airport", city:"Vadodara", state:"Gujarat", lat:22.3362, lon:73.2263, type:"domestic", passengers:1200000, cargo:1500, movements:12000, runways:1, longestRunwayFt:8000, elevationFt:127, operator:"AAI", opened:2016, airlines:["IndiGo","SpiceJet","Air India"], topRoutes:["DEL","BOM","AMD"], terminals:1, parkingBays:4, fuelType:"Jet A-1", avgDailyFlights:33, internationalShare:0, cargoShare:0, hubFor:[""], notables:"New terminal opened 2016." },
  { iata:"BHJ", icao:"VABV", name:"Bhuj Airport", city:"Bhuj", state:"Gujarat", lat:23.2879, lon:69.6707, type:"domestic", passengers:200000, cargo:0, movements:3000, runways:1, longestRunwayFt:8000, elevationFt:248, operator:"Indian Air Force / AAI", opened:2000, airlines:["SpiceJet"], topRoutes:["DEL","BOM","AMD"], terminals:1, parkingBays:2, fuelType:"Jet A-1", avgDailyFlights:6, internationalShare:0, cargoShare:0, hubFor:[""], notables:"Joint civil-military. Near Pakistan border." },
  { iata:"JLR", icao:"VAJB", name:"Jabalpur Airport (Dumna)", city:"Jabalpur", state:"Madhya Pradesh", lat:23.1778, lon:80.0522, type:"domestic", passengers:300000, cargo:0, movements:5000, runways:1, longestRunwayFt:6900, elevationFt:1624, operator:"AAI", opened:1946, airlines:["IndiGo","Air India","SpiceJet"], topRoutes:["DEL","BOM","HYD"], terminals:1, parkingBays:3, fuelType:"Jet A-1", avgDailyFlights:10, internationalShare:0, cargoShare:0, hubFor:[""], notables:"Serves Marble City. Near Khajuraho temples." },
  { iata:"GWL", icao:"VIGR", name:"Gwalior Airport", city:"Gwalior", state:"Madhya Pradesh", lat:26.2933, lon:78.2278, type:"domestic", passengers:500000, cargo:0, movements:8000, runways:1, longestRunwayFt:9000, elevationFt:617, operator:"Indian Air Force / AAI", opened:1937, airlines:["IndiGo","SpiceJet"], topRoutes:["DEL","BOM","JAI"], terminals:1, parkingBays:4, fuelType:"Jet A-1", avgDailyFlights:15, internationalShare:0, cargoShare:0, hubFor:[""], notables:"Joint civil-military. Largest IAF base." },
  { iata:"IXD", icao:"VIAL", name:"Prayagraj Airport (Bamrauli)", city:"Prayagraj", state:"Uttar Pradesh", lat:25.4401, lon:81.7339, type:"domestic", passengers:400000, cargo:0, movements:6000, runways:1, longestRunwayFt:8000, elevationFt:322, operator:"Indian Air Force / AAI", opened:1966, airlines:["IndiGo","SpiceJet"], topRoutes:["DEL","BOM","CCU"], terminals:1, parkingBays:3, fuelType:"Jet A-1", avgDailyFlights:12, internationalShare:0, cargoShare:0, hubFor:[""], notables:"Serves Triveni Sangam city." },
  { iata:"HJR", icao:"VAKJ", name:"Khajuraho Airport", city:"Khajuraho", state:"Madhya Pradesh", lat:24.8172, lon:79.9186, type:"domestic", passengers:100000, cargo:0, movements:1500, runways:1, longestRunwayFt:7000, elevationFt:738, operator:"AAI", opened:1983, airlines:["SpiceJet","IndiGo"], topRoutes:["DEL","BOM","JAI","VNS"], terminals:1, parkingBays:2, fuelType:"Jet A-1", avgDailyFlights:3, internationalShare:0, cargoShare:0, hubFor:[""], notables:"Serves UNESCO World Heritage temples." },
];

// Merge all unique airports
export const FINAL_AIRPORTS = [...ALL_AIRPORTS, ...MORE_AIRPORTS].filter(
  (a, i, arr) => arr.findIndex(x => x.iata === a.iata) === i
);

export const AIRPORT_STATS_FINAL = {
  totalAirports: FINAL_AIRPORTS.length,
  activeAirports: FINAL_AIRPORTS.filter(a => a.passengers > 0).length,
  upcomingAirports: FINAL_AIRPORTS.filter(a => a.passengers === 0).length,
  totalPassengers: FINAL_AIRPORTS.reduce((s, a) => s + a.passengers, 0),
  totalCargo: FINAL_AIRPORTS.reduce((s, a) => s + a.cargo, 0),
  totalMovements: FINAL_AIRPORTS.reduce((s, a) => s + a.movements, 0),
  statesCovered: new Set(FINAL_AIRPORTS.map(a => a.state)).size,
  totalRunways: FINAL_AIRPORTS.reduce((s, a) => s + a.runways, 0),
  avgDailyFlights: FINAL_AIRPORTS.reduce((s, a) => s + a.avgDailyFlights, 0),
};
