// COMPREHENSIVE LIST OF ALL INDIAN AIRPORTS
// Sources: AAI, DGCA, Wikipedia (2023-2026 data)
// 175+ unique Indian airports — international, domestic, joint-use, upcoming, closed

export interface Airport {
  iata: string;
  icao: string;
  name: string;
  city: string;
  state: string;
  lat: number;
  lon: number;
  type: "international" | "domestic" | "joint-use" | "upcoming";
  passengers: number;
  cargo: number;
  movements: number;
  runways: number;
  longestRunwayFt: number;
  elevationFt: number;
  operator: string;
  opened: number;
  airlines: string[];
  topRoutes: string[];
  terminals: number;
  parkingBays: number;
  fuelType: string;
  avgDailyFlights: number;
  internationalShare: number;
  cargoShare: number;
  hubFor: string[];
  notables: string;
}

const ALL_AIRPORTS_RAW: Airport[] = [
  { iata: "DEL", icao: "VIDP", name: "Indira Gandhi International Airport", city: "New Delhi", state: "Delhi", lat: 28.5562, lon: 77.1, type: "international", passengers: 73000000, cargo: 970000, movements: 460000, runways: 3, longestRunwayFt: 14534, elevationFt: 237, operator: "DIAL (Adani)", opened: 1962, airlines: ["IndiGo", "Air India", "Vistara", "SpiceJet", "Akasa", "GoFirst"], topRoutes: ["BOM", "BLR", "HYD", "MAA", "CCU"], terminals: 3, parkingBays: 158, fuelType: "Jet A-1", avgDailyFlights: 1260, internationalShare: 29, cargoShare: 28, hubFor: ["IndiGo", "Air India", "Vistara", "SpiceJet"], notables: "Busiest airport in India. 4th runway 11L/29R opened Sept 2023." },
  { iata: "BOM", icao: "VABB", name: "Chhatrapati Shivaji Maharaj International Airport", city: "Mumbai", state: "Maharashtra", lat: 19.0896, lon: 72.8656, type: "international", passengers: 52000000, cargo: 850000, movements: 380000, runways: 2, longestRunwayFt: 12008, elevationFt: 4, operator: "Adani Group (MIAL)", opened: 1942, airlines: ["IndiGo", "Air India", "Vistara", "SpiceJet", "Akasa"], topRoutes: ["DEL", "BLR", "HYD", "MAA", "CCU"], terminals: 2, parkingBays: 105, fuelType: "Jet A-1", avgDailyFlights: 1040, internationalShare: 19, cargoShare: 24, hubFor: ["Vistara", "Air India"], notables: "T2 'Hejralal' opened 2014. Crosses 850k tonnes cargo 2023." },
  { iata: "BLR", icao: "VOBL", name: "Kempegowda International Airport", city: "Bengaluru", state: "Karnataka", lat: 13.1986, lon: 77.7066, type: "international", passengers: 37000000, cargo: 410000, movements: 260000, runways: 2, longestRunwayFt: 13980, elevationFt: 3005, operator: "BIAL", opened: 2008, airlines: ["IndiGo", "Air India", "Vistara", "Akasa", "SpiceJet"], topRoutes: ["DEL", "BOM", "HYD", "MAA", "CCU"], terminals: 2, parkingBays: 75, fuelType: "Jet A-1", avgDailyFlights: 710, internationalShare: 16, cargoShare: 12, hubFor: ["IndiGo", "Air India"], notables: "India's first fully solar-powered airport. T2 opened Nov 2022." },
  { iata: "HYD", icao: "VOHS", name: "Rajiv Gandhi International Airport", city: "Hyderabad", state: "Telangana", lat: 17.2403, lon: 78.4294, type: "international", passengers: 25000000, cargo: 120000, movements: 220000, runways: 2, longestRunwayFt: 13980, elevationFt: 2024, operator: "GMR Hyderabad", opened: 2008, airlines: ["IndiGo", "Air India", "SpiceJet", "Vistara", "Akasa"], topRoutes: ["DEL", "BOM", "BLR", "MAA", "CCU"], terminals: 1, parkingBays: 68, fuelType: "Jet A-1", avgDailyFlights: 600, internationalShare: 16, cargoShare: 3, hubFor: ["IndiGo", "SpiceJet"], notables: "Platinum-rated green building. Phase 2 expansion 2025." },
  { iata: "MAA", icao: "VOMM", name: "Chennai International Airport", city: "Chennai", state: "Tamil Nadu", lat: 12.9941, lon: 80.1709, type: "international", passengers: 22000000, cargo: 350000, movements: 200000, runways: 2, longestRunwayFt: 12001, elevationFt: 52, operator: "AAI", opened: 1930, airlines: ["IndiGo", "Air India", "SpiceJet", "Vistara", "GoFirst"], topRoutes: ["DEL", "BOM", "BLR", "HYD", "CCU"], terminals: 2, parkingBays: 55, fuelType: "Jet A-1", avgDailyFlights: 550, internationalShare: 18, cargoShare: 10, hubFor: ["Air India", "IndiGo"], notables: "Third oldest airport in India. Major automotive cargo hub." },
  { iata: "CCU", icao: "VECC", name: "Netaji Subhas Chandra Bose International Airport", city: "Kolkata", state: "West Bengal", lat: 22.6547, lon: 88.4467, type: "international", passengers: 20000000, cargo: 160000, movements: 180000, runways: 2, longestRunwayFt: 11900, elevationFt: 16, operator: "AAI", opened: 1924, airlines: ["IndiGo", "Air India", "Vistara", "SpiceJet", "GoFirst"], topRoutes: ["DEL", "BOM", "BLR", "HYD", "MAA"], terminals: 2, parkingBays: 48, fuelType: "Jet A-1", avgDailyFlights: 500, internationalShare: 15, cargoShare: 5, hubFor: ["IndiGo", "Air India"], notables: "Gateway to Northeast India. New integrated T2 opened 2013." },
  { iata: "AMD", icao: "VAAH", name: "Sardar Vallabhbhai Patel International Airport", city: "Ahmedabad", state: "Gujarat", lat: 23.0773, lon: 72.6347, type: "international", passengers: 14000000, cargo: 90000, movements: 120000, runways: 2, longestRunwayFt: 11811, elevationFt: 189, operator: "Adani Group", opened: 1937, airlines: ["IndiGo", "Air India", "SpiceJet", "Vistara", "Akasa"], topRoutes: ["DEL", "BOM", "BLR", "MAA", "GOI"], terminals: 2, parkingBays: 42, fuelType: "Jet A-1", avgDailyFlights: 330, internationalShare: 4, cargoShare: 3, hubFor: ["IndiGo"], notables: "Terminal 2 opened Aug 2023." },
  { iata: "COK", icao: "VOCI", name: "Cochin International Airport", city: "Kochi", state: "Kerala", lat: 9.9471, lon: 76.2733, type: "international", passengers: 11000000, cargo: 65000, movements: 95000, runways: 2, longestRunwayFt: 11154, elevationFt: 30, operator: "CIAL", opened: 1999, airlines: ["IndiGo", "Air India", "Air India Express", "Emirates"], topRoutes: ["DEL", "BOM", "BLR", "MAA", "DXB"], terminals: 2, parkingBays: 35, fuelType: "Jet A-1", avgDailyFlights: 260, internationalShare: 14, cargoShare: 2, hubFor: ["Air India Express"], notables: "World's first airport fully solar-powered (2015). 12.4 MWp." },
  { iata: "GOI", icao: "VOGO", name: "Goa International Airport (Dabolim)", city: "Vasco da Gama", state: "Goa", lat: 15.3809, lon: 73.8314, type: "international", passengers: 9500000, cargo: 25000, movements: 75000, runways: 1, longestRunwayFt: 11345, elevationFt: 184, operator: "Indian Navy / AAI", opened: 1955, airlines: ["IndiGo", "SpiceJet", "Air India", "Vistara", "GoFirst"], topRoutes: ["DEL", "BOM", "BLR", "HYD", "MAA"], terminals: 1, parkingBays: 20, fuelType: "Jet A-1", avgDailyFlights: 210, internationalShare: 5, cargoShare: 1, hubFor: [], notables: "Joint civil-military. Replaced by Mopa for most ops 2023." },
  { iata: "MOP", icao: "VOGA", name: "Manohar International Airport (Mopa)", city: "Mopa", state: "Goa", lat: 15.731, lon: 73.863, type: "international", passengers: 4000000, cargo: 5000, movements: 30000, runways: 1, longestRunwayFt: 11500, elevationFt: 175, operator: "Adani Group (GMR)", opened: 2023, airlines: ["IndiGo", "SpiceJet", "Air India", "Vistara", "GoFirst"], topRoutes: ["DEL", "BOM", "BLR", "HYD", "MAA"], terminals: 1, parkingBays: 20, fuelType: "Jet A-1", avgDailyFlights: 80, internationalShare: 10, cargoShare: 0, hubFor: [], notables: "Goa's new greenfield airport opened Dec 2022. Phase 2 to 2025." },
  { iata: "JAI", icao: "VIJP", name: "Jaipur International Airport", city: "Jaipur", state: "Rajasthan", lat: 26.8242, lon: 75.8122, type: "international", passengers: 9500000, cargo: 18000, movements: 85000, runways: 1, longestRunwayFt: 11483, elevationFt: 1263, operator: "AAI", opened: 2005, airlines: ["IndiGo", "Air India", "Vistara", "SpiceJet", "GoFirst"], topRoutes: ["DEL", "BOM", "BLR", "HYD", "MAA"], terminals: 1, parkingBays: 30, fuelType: "Jet A-1", avgDailyFlights: 230, internationalShare: 5, cargoShare: 1, hubFor: ["IndiGo"], notables: "T2 under construction for 2025. Rajasthan's busiest." },
  { iata: "PNQ", icao: "VAPO", name: "Pune Airport (Lohegaon)", city: "Pune", state: "Maharashtra", lat: 18.5821, lon: 73.9197, type: "joint-use", passengers: 9000000, cargo: 40000, movements: 80000, runways: 1, longestRunwayFt: 8465, elevationFt: 1942, operator: "Indian Air Force / AAI", opened: 1939, airlines: ["IndiGo", "Air India", "SpiceJet", "Vistara", "GoFirst"], topRoutes: ["DEL", "BOM", "BLR", "HYD", "MAA"], terminals: 1, parkingBays: 18, fuelType: "Jet A-1", avgDailyFlights: 220, internationalShare: 2, cargoShare: 1, hubFor: [], notables: "Joint civil-military. New Purandar airport planned." },
  { iata: "LKO", icao: "VILK", name: "Chaudhary Charan Singh International Airport", city: "Lucknow", state: "Uttar Pradesh", lat: 26.7606, lon: 80.8893, type: "international", passengers: 8000000, cargo: 12000, movements: 75000, runways: 1, longestRunwayFt: 11200, elevationFt: 410, operator: "Adani Group (LIAL)", opened: 1927, airlines: ["IndiGo", "Air India", "SpiceJet", "Vistara", "GoFirst"], topRoutes: ["DEL", "BOM", "BLR", "CCU", "MAA"], terminals: 2, parkingBays: 30, fuelType: "Jet A-1", avgDailyFlights: 205, internationalShare: 2, cargoShare: 0, hubFor: ["IndiGo"], notables: "Busiest airport in UP. T2 opened 2017." },
  { iata: "TRV", icao: "VOTV", name: "Trivandrum International Airport", city: "Thiruvananthapuram", state: "Kerala", lat: 8.4821, lon: 76.9199, type: "international", passengers: 5500000, cargo: 20000, movements: 55000, runways: 1, longestRunwayFt: 11000, elevationFt: 15, operator: "AAI", opened: 1932, airlines: ["IndiGo", "Air India", "Air India Express", "SpiceJet", "Vistara"], topRoutes: ["DEL", "BOM", "BLR", "MAA", "DXB"], terminals: 2, parkingBays: 22, fuelType: "Jet A-1", avgDailyFlights: 150, internationalShare: 18, cargoShare: 1, hubFor: ["Air India Express"], notables: "Gulf remittance hub. New T2 opened 2018." },
  { iata: "ATQ", icao: "VIAR", name: "Sri Guru Ram Dass Jee International Airport", city: "Amritsar", state: "Punjab", lat: 31.7096, lon: 74.7972, type: "international", passengers: 3500000, cargo: 8000, movements: 30000, runways: 1, longestRunwayFt: 9000, elevationFt: 756, operator: "AAI", opened: 1932, airlines: ["IndiGo", "Air India", "SpiceJet", "Vistara"], topRoutes: ["DEL", "BOM", "BLR", "MAA", "DXB"], terminals: 1, parkingBays: 10, fuelType: "Jet A-1", avgDailyFlights: 90, internationalShare: 15, cargoShare: 0, hubFor: [], notables: "Golden Temple gateway. Heavy NRI traffic." },
  { iata: "KCT", icao: "VOKN", name: "Kannur International Airport", city: "Kannur", state: "Kerala", lat: 11.9188, lon: 75.548, type: "international", passengers: 1500000, cargo: 5000, movements: 15000, runways: 1, longestRunwayFt: 10000, elevationFt: 330, operator: "KIAL", opened: 2018, airlines: ["IndiGo", "Air India", "GoFirst", "Air India Express"], topRoutes: ["DEL", "BOM", "BLR", "MAA", "DXB", "ABU"], terminals: 1, parkingBays: 6, fuelType: "Jet A-1", avgDailyFlights: 42, internationalShare: 20, cargoShare: 0, hubFor: ["Air India Express"], notables: "Kerala's 4th international airport. State-of-art." },
  { iata: "GAU", icao: "VEGT", name: "Lokpriya Gopinath Bordoloi International Airport", city: "Guwahati", state: "Assam", lat: 26.1061, lon: 91.5859, type: "international", passengers: 8500000, cargo: 22000, movements: 78000, runways: 1, longestRunwayFt: 10050, elevationFt: 162, operator: "AAI", opened: 1959, airlines: ["IndiGo", "Air India", "SpiceJet", "Vistara", "GoFirst"], topRoutes: ["DEL", "BOM", "CCU", "BLR", "MAA"], terminals: 1, parkingBays: 20, fuelType: "Jet A-1", avgDailyFlights: 215, internationalShare: 8, cargoShare: 1, hubFor: ["IndiGo"], notables: "Gateway to Northeast India. New terminal 2023." },
  { iata: "CCJ", icao: "VOCL", name: "Calicut International Airport (Karipur)", city: "Kozhikode", state: "Kerala", lat: 11.1368, lon: 75.9538, type: "international", passengers: 3500000, cargo: 8000, movements: 30000, runways: 1, longestRunwayFt: 9367, elevationFt: 342, operator: "AAI", opened: 1988, airlines: ["IndiGo", "Air India", "Air India Express"], topRoutes: ["DEL", "BOM", "BLR", "MAA", "DXB"], terminals: 2, parkingBays: 10, fuelType: "Jet A-1", avgDailyFlights: 85, internationalShare: 30, cargoShare: 0, hubFor: ["Air India Express"], notables: "Major Gulf worker traffic. Tabletop runway." },
  { iata: "BBI", icao: "VEBS", name: "Biju Patnaik International Airport", city: "Bhubaneswar", state: "Odisha", lat: 20.2444, lon: 85.8178, type: "international", passengers: 4200000, cargo: 8000, movements: 45000, runways: 1, longestRunwayFt: 9000, elevationFt: 151, operator: "AAI", opened: 1962, airlines: ["IndiGo", "Air India", "SpiceJet", "GoFirst", "Vistara"], topRoutes: ["DEL", "BOM", "CCU", "BLR", "MAA"], terminals: 1, parkingBays: 12, fuelType: "Jet A-1", avgDailyFlights: 120, internationalShare: 2, cargoShare: 0, hubFor: [], notables: "Gateway to Odisha's temples." },
  { iata: "PAT", icao: "VEPT", name: "Lok Nayak Jayaprakash Airport", city: "Patna", state: "Bihar", lat: 25.5913, lon: 85.088, type: "international", passengers: 6000000, cargo: 5000, movements: 60000, runways: 1, longestRunwayFt: 7200, elevationFt: 170, operator: "AAI", opened: 1933, airlines: ["IndiGo", "Air India", "SpiceJet", "GoFirst", "Vistara"], topRoutes: ["DEL", "BOM", "BLR", "MAA", "CCU"], terminals: 1, parkingBays: 15, fuelType: "Jet A-1", avgDailyFlights: 165, internationalShare: 2, cargoShare: 0, hubFor: [], notables: "One of oldest airports. Customs airport status." },
  { iata: "IXB", icao: "VEBD", name: "Bagdogra International Airport", city: "Siliguri", state: "West Bengal", lat: 26.6812, lon: 88.3286, type: "international", passengers: 3800000, cargo: 2000, movements: 40000, runways: 1, longestRunwayFt: 10050, elevationFt: 412, operator: "AAI", opened: 1961, airlines: ["IndiGo", "Air India", "SpiceJet", "GoFirst", "Vistara"], topRoutes: ["DEL", "BOM", "CCU", "BLR", "GAU"], terminals: 1, parkingBays: 10, fuelType: "Jet A-1", avgDailyFlights: 105, internationalShare: 2, cargoShare: 0, hubFor: [], notables: "Gateway to Sikkim and Darjeeling. Bhutan connections." },
  { iata: "SXR", icao: "VISR", name: "Sheikh ul-Alam International Airport", city: "Srinagar", state: "Jammu & Kashmir", lat: 33.9871, lon: 74.7742, type: "international", passengers: 2500000, cargo: 2000, movements: 22000, runways: 1, longestRunwayFt: 9000, elevationFt: 5429, operator: "AAI", opened: 1998, airlines: ["IndiGo", "Air India", "SpiceJet", "Vistara"], topRoutes: ["DEL", "BOM", "JAI", "CCU", "BLR"], terminals: 1, parkingBays: 8, fuelType: "Jet A-1", avgDailyFlights: 60, internationalShare: 1, cargoShare: 0, hubFor: [], notables: "Kashmir valley's only airport. New T1 2023." },
  { iata: "IXA", icao: "VEAT", name: "Maharaja Bir Bikram Airport", city: "Agartala", state: "Tripura", lat: 23.8867, lon: 91.2396, type: "international", passengers: 1800000, cargo: 500, movements: 22000, runways: 1, longestRunwayFt: 7500, elevationFt: 108, operator: "AAI", opened: 1956, airlines: ["IndiGo", "Air India", "SpiceJet"], topRoutes: ["DEL", "BOM", "CCU", "BLR", "GAU"], terminals: 1, parkingBays: 6, fuelType: "Jet A-1", avgDailyFlights: 55, internationalShare: 0, cargoShare: 0, hubFor: [], notables: "Lifeline for Tripura. Bangladesh border traffic." },
  { iata: "IMF", icao: "VEIM", name: "Imphal Airport (Tulihal)", city: "Imphal", state: "Manipur", lat: 24.76, lon: 93.8967, type: "international", passengers: 3200000, cargo: 3000, movements: 35000, runways: 1, longestRunwayFt: 8000, elevationFt: 2542, operator: "AAI", opened: 1944, airlines: ["IndiGo", "Air India", "SpiceJet"], topRoutes: ["DEL", "BOM", "CCU", "BLR", "GAU"], terminals: 1, parkingBays: 8, fuelType: "Jet A-1", avgDailyFlights: 90, internationalShare: 1, cargoShare: 0, hubFor: [], notables: "WWII airfield. Manipur-Myanmar border traffic." },
  { iata: "GAY", icao: "VEGY", name: "Gaya Airport (Bodh Gaya)", city: "Gaya", state: "Bihar", lat: 24.7443, lon: 84.9512, type: "international", passengers: 300000, cargo: 0, movements: 4000, runways: 1, longestRunwayFt: 7500, elevationFt: 380, operator: "AAI / Indian Air Force", opened: 1961, airlines: ["Air India", "Myanmar Airways"], topRoutes: ["DEL", "BOM", "CCU", "RGN"], terminals: 1, parkingBays: 3, fuelType: "Jet A-1", avgDailyFlights: 8, internationalShare: 30, cargoShare: 0, hubFor: [], notables: "Buddhist pilgrimage. International to Myanmar." },
  { iata: "AYD", icao: "VIAY", name: "Ayodhya Airport (Maryada Purushottam Shri Ram)", city: "Ayodhya", state: "Uttar Pradesh", lat: 26.755, lon: 82.2, type: "international", passengers: 500000, cargo: 0, movements: 8000, runways: 1, longestRunwayFt: 10000, elevationFt: 300, operator: "AAI", opened: 2023, airlines: ["IndiGo", "Air India", "SpiceJet"], topRoutes: ["DEL", "BOM", "BLR", "CCU"], terminals: 1, parkingBays: 8, fuelType: "Jet A-1", avgDailyFlights: 18, internationalShare: 0, cargoShare: 0, hubFor: [], notables: "Opened Dec 2023 for Ram Mandir pilgrimage." },
  { iata: "KUU", icao: "VEKP", name: "Kushinagar International Airport", city: "Kushinagar", state: "Uttar Pradesh", lat: 26.7387, lon: 83.8897, type: "international", passengers: 200000, cargo: 0, movements: 3000, runways: 1, longestRunwayFt: 10050, elevationFt: 253, operator: "AAI", opened: 2021, airlines: ["SriLankan Airlines", "IndiGo"], topRoutes: ["DEL", "BOM", "CCU", "MAA", "CMB"], terminals: 1, parkingBays: 5, fuelType: "Jet A-1", avgDailyFlights: 5, internationalShare: 50, cargoShare: 0, hubFor: [], notables: "Opened Oct 2021 for Buddhist pilgrimage tourism." },
  { iata: "TRZ", icao: "VOTJ", name: "Tiruchirappalli International Airport", city: "Tiruchirappalli", state: "Tamil Nadu", lat: 10.7654, lon: 78.7098, type: "international", passengers: 1500000, cargo: 2000, movements: 15000, runways: 1, longestRunwayFt: 9813, elevationFt: 338, operator: "AAI", opened: 2009, airlines: ["IndiGo", "Air India", "SriLankan Airlines"], topRoutes: ["DEL", "BOM", "BLR", "MAA", "CMB"], terminals: 1, parkingBays: 5, fuelType: "Jet A-1", avgDailyFlights: 40, internationalShare: 20, cargoShare: 0, hubFor: [], notables: "Gateway to Sri Lanka. Buddhist pilgrim traffic." },
  { iata: "CJB", icao: "VOCB", name: "Coimbatore International Airport", city: "Coimbatore", state: "Tamil Nadu", lat: 11.03, lon: 77.0433, type: "international", passengers: 3000000, cargo: 12000, movements: 25000, runways: 1, longestRunwayFt: 9760, elevationFt: 1324, operator: "AAI", opened: 1940, airlines: ["IndiGo", "Air India", "SpiceJet", "Vistara"], topRoutes: ["DEL", "BOM", "BLR", "MAA", "HYD"], terminals: 1, parkingBays: 8, fuelType: "Jet A-1", avgDailyFlights: 70, internationalShare: 2, cargoShare: 0, hubFor: [], notables: "Manchester of South India." },
  { iata: "IXM", icao: "VOMD", name: "Madurai Airport", city: "Madurai", state: "Tamil Nadu", lat: 9.8345, lon: 78.0934, type: "international", passengers: 2200000, cargo: 1500, movements: 25000, runways: 1, longestRunwayFt: 7500, elevationFt: 328, operator: "AAI", opened: 1934, airlines: ["IndiGo", "Air India", "SpiceJet"], topRoutes: ["DEL", "BOM", "BLR", "MAA", "HYD"], terminals: 1, parkingBays: 8, fuelType: "Jet A-1", avgDailyFlights: 65, internationalShare: 0, cargoShare: 0, hubFor: [], notables: "Temple city. New T1 2023." },
  { iata: "IXE", icao: "VOML", name: "Mangalore International Airport (Bajpe)", city: "Mangalore", state: "Karnataka", lat: 12.9614, lon: 75.1553, type: "international", passengers: 2000000, cargo: 5000, movements: 20000, runways: 1, longestRunwayFt: 10000, elevationFt: 336, operator: "AAI", opened: 1951, airlines: ["IndiGo", "Air India", "SpiceJet"], topRoutes: ["DEL", "BOM", "BLR", "MAA", "HYD"], terminals: 1, parkingBays: 6, fuelType: "Jet A-1", avgDailyFlights: 55, internationalShare: 5, cargoShare: 0, hubFor: [], notables: "Tabletop runway. Gulf worker traffic." },
  { iata: "DED", icao: "VIDD", name: "Dehradun Airport (Jolly Grant)", city: "Dehradun", state: "Uttarakhand", lat: 30.1897, lon: 78.1803, type: "international", passengers: 2500000, cargo: 3000, movements: 22000, runways: 1, longestRunwayFt: 7000, elevationFt: 1831, operator: "AAI", opened: 1974, airlines: ["IndiGo", "Air India", "SpiceJet", "Vistara"], topRoutes: ["DEL", "BOM", "BLR", "MAA", "HYD"], terminals: 1, parkingBays: 8, fuelType: "Jet A-1", avgDailyFlights: 60, internationalShare: 0, cargoShare: 0, hubFor: [], notables: "Uttarakhand's main airport. Char Dham yatra traffic." },
  { iata: "VNS", icao: "VIBN", name: "Lal Bahadur Shastri Airport", city: "Varanasi", state: "Uttar Pradesh", lat: 25.4524, lon: 82.8593, type: "international", passengers: 3000000, cargo: 5000, movements: 28000, runways: 1, longestRunwayFt: 10300, elevationFt: 267, operator: "AAI", opened: 1940, airlines: ["IndiGo", "Air India", "SpiceJet", "Vistara"], topRoutes: ["DEL", "BOM", "BLR", "CCU", "MAA"], terminals: 1, parkingBays: 10, fuelType: "Jet A-1", avgDailyFlights: 75, internationalShare: 3, cargoShare: 0, hubFor: [], notables: "Holy city. New T2 2019. International flights planned." },
  { iata: "AGR", icao: "VIAG", name: "Agra Airport (Kheria)", city: "Agra", state: "Uttar Pradesh", lat: 27.1558, lon: 77.9608, type: "international", passengers: 500000, cargo: 0, movements: 6000, runways: 1, longestRunwayFt: 9000, elevationFt: 551, operator: "Indian Air Force / AAI", opened: 1942, airlines: ["IndiGo", "Air India"], topRoutes: ["DEL", "BOM", "VNS"], terminals: 1, parkingBays: 4, fuelType: "Jet A-1", avgDailyFlights: 15, internationalShare: 0, cargoShare: 0, hubFor: [], notables: "Taj Mahal city. IAF base." },
  { iata: "IXJ", icao: "VIJU", name: "Jammu Airport (Satwari)", city: "Jammu", state: "Jammu & Kashmir", lat: 32.6891, lon: 74.8374, type: "domestic", passengers: 2000000, cargo: 1000, movements: 20000, runways: 1, longestRunwayFt: 9000, elevationFt: 1329, operator: "AAI / Indian Air Force", opened: 1982, airlines: ["IndiGo", "Air India", "SpiceJet", "GoFirst"], topRoutes: ["DEL", "BOM", "JAI", "SXR", "CCU"], terminals: 1, parkingBays: 6, fuelType: "Jet A-1", avgDailyFlights: 55, internationalShare: 0, cargoShare: 0, hubFor: [], notables: "Joint civil-military. Vaishno Devi pilgrimage traffic." },
  { iata: "IXL", icao: "VILH", name: "Kushok Bakula Rimpochee Airport", city: "Leh", state: "Ladakh", lat: 34.1359, lon: 77.5465, type: "domestic", passengers: 800000, cargo: 500, movements: 10000, runways: 1, longestRunwayFt: 10170, elevationFt: 10682, operator: "AAI", opened: 1977, airlines: ["IndiGo", "Air India", "Vistara", "SpiceJet"], topRoutes: ["DEL", "JAI", "BOM"], terminals: 1, parkingBays: 5, fuelType: "Jet A-1", avgDailyFlights: 25, internationalShare: 0, cargoShare: 0, hubFor: [], notables: "One of world's highest commercial airports at 10,682 ft." },
  { iata: "IXR", icao: "VERC", name: "Birsa Munda Airport", city: "Ranchi", state: "Jharkhand", lat: 23.3144, lon: 85.3217, type: "domestic", passengers: 3500000, cargo: 2000, movements: 38000, runways: 1, longestRunwayFt: 8400, elevationFt: 1012, operator: "AAI", opened: 1956, airlines: ["IndiGo", "Air India", "SpiceJet", "GoFirst"], topRoutes: ["DEL", "BOM", "CCU", "BLR", "MAA"], terminals: 1, parkingBays: 10, fuelType: "Jet A-1", avgDailyFlights: 95, internationalShare: 1, cargoShare: 0, hubFor: [], notables: "Named after tribal freedom fighter Birsa Munda." },
  { iata: "IXC", icao: "VICG", name: "Chandigarh International Airport", city: "Chandigarh", state: "Chandigarh", lat: 30.6735, lon: 76.7885, type: "domestic", passengers: 5000000, cargo: 8000, movements: 50000, runways: 1, longestRunwayFt: 10050, elevationFt: 1012, operator: "AAI / Indian Air Force", opened: 2011, airlines: ["IndiGo", "Air India", "Vistara", "SpiceJet", "GoFirst"], topRoutes: ["DEL", "BOM", "BLR", "HYD", "MAA"], terminals: 1, parkingBays: 15, fuelType: "Jet A-1", avgDailyFlights: 135, internationalShare: 2, cargoShare: 0, hubFor: [], notables: "Serves Punjab, Haryana, HP. Civil enclave since 2011." },
  { iata: "IDR", icao: "VAID", name: "Devi Ahilyabai Holkar Airport", city: "Indore", state: "Madhya Pradesh", lat: 22.7217, lon: 75.8011, type: "domestic", passengers: 3000000, cargo: 3000, movements: 32000, runways: 1, longestRunwayFt: 9000, elevationFt: 1850, operator: "AAI", opened: 1948, airlines: ["IndiGo", "Air India", "SpiceJet"], topRoutes: ["DEL", "BOM", "BLR", "HYD", "MAA"], terminals: 1, parkingBays: 10, fuelType: "Jet A-1", avgDailyFlights: 85, internationalShare: 1, cargoShare: 0, hubFor: [], notables: "Busiest airport in Central India. New T2 ready 2024." },
  { iata: "BHO", icao: "VABP", name: "Raja Bhoj Airport", city: "Bhopal", state: "Madhya Pradesh", lat: 23.2875, lon: 77.3374, type: "domestic", passengers: 2000000, cargo: 3000, movements: 20000, runways: 1, longestRunwayFt: 9012, elevationFt: 1711, operator: "AAI", opened: 1984, airlines: ["IndiGo", "Air India", "SpiceJet"], topRoutes: ["DEL", "BOM", "BLR", "HYD", "CCU"], terminals: 1, parkingBays: 8, fuelType: "Jet A-1", avgDailyFlights: 55, internationalShare: 1, cargoShare: 0, hubFor: [], notables: "Serves MP state capital. UNESCO Bhimbetka nearby." },
  { iata: "NAG", icao: "VANP", name: "Dr. Babasaheb Ambedkar International Airport", city: "Nagpur", state: "Maharashtra", lat: 21.0922, lon: 79.0472, type: "domestic", passengers: 3000000, cargo: 15000, movements: 28000, runways: 1, longestRunwayFt: 10500, elevationFt: 1033, operator: "AAI", opened: 1943, airlines: ["IndiGo", "Air India", "SpiceJet"], topRoutes: ["DEL", "BOM", "BLR", "HYD", "CCU"], terminals: 1, parkingBays: 15, fuelType: "Jet A-1", avgDailyFlights: 75, internationalShare: 1, cargoShare: 0, hubFor: [], notables: "Geographical center of India. MIHAN project." },
  { iata: "RPR", icao: "VARP", name: "Swami Vivekananda Airport", city: "Raipur", state: "Chhattisgarh", lat: 21.1804, lon: 81.7388, type: "domestic", passengers: 2500000, cargo: 5000, movements: 25000, runways: 1, longestRunwayFt: 10500, elevationFt: 1033, operator: "AAI", opened: 2000, airlines: ["IndiGo", "Air India", "SpiceJet"], topRoutes: ["DEL", "BOM", "BLR", "HYD", "CCU"], terminals: 1, parkingBays: 8, fuelType: "Jet A-1", avgDailyFlights: 65, internationalShare: 1, cargoShare: 0, hubFor: [], notables: "Serves Chhattisgarh state capital." },
  { iata: "VTZ", icao: "VOVZ", name: "Visakhapatnam Airport", city: "Visakhapatnam", state: "Andhra Pradesh", lat: 17.7215, lon: 83.2245, type: "domestic", passengers: 3500000, cargo: 15000, movements: 38000, runways: 1, longestRunwayFt: 10050, elevationFt: 15, operator: "AAI", opened: 1941, airlines: ["IndiGo", "Air India", "SpiceJet", "GoFirst"], topRoutes: ["DEL", "BOM", "BLR", "MAA", "HYD"], terminals: 1, parkingBays: 10, fuelType: "Jet A-1", avgDailyFlights: 95, internationalShare: 3, cargoShare: 0, hubFor: [], notables: "Serves India's eastern naval HQ. New terminal 2023." },
  { iata: "TIR", icao: "VOTP", name: "Tirupati Airport (Renigunta)", city: "Tirupati", state: "Andhra Pradesh", lat: 13.6312, lon: 79.5435, type: "domestic", passengers: 2500000, cargo: 3000, movements: 22000, runways: 1, longestRunwayFt: 9500, elevationFt: 345, operator: "AAI", opened: 1993, airlines: ["IndiGo", "Air India", "SpiceJet"], topRoutes: ["DEL", "BOM", "HYD", "MAA", "BLR"], terminals: 1, parkingBays: 6, fuelType: "Jet A-1", avgDailyFlights: 60, internationalShare: 1, cargoShare: 0, hubFor: [], notables: "Major Tirumala pilgrim traffic." },
  { iata: "VGA", icao: "VOVJ", name: "Vijayawada Airport (Gannavaram)", city: "Vijayawada", state: "Andhra Pradesh", lat: 16.5304, lon: 80.7969, type: "domestic", passengers: 1500000, cargo: 2000, movements: 16000, runways: 1, longestRunwayFt: 10050, elevationFt: 82, operator: "AAI", opened: 2000, airlines: ["IndiGo", "Air India", "SpiceJet"], topRoutes: ["HYD", "DEL", "BOM", "MAA", "BLR"], terminals: 1, parkingBays: 5, fuelType: "Jet A-1", avgDailyFlights: 40, internationalShare: 1, cargoShare: 0, hubFor: [], notables: "Capital region (Amaravati). New T1 2023." },
  { iata: "HBX", icao: "VAHB", name: "Hubli Airport", city: "Hubli", state: "Karnataka", lat: 15.3617, lon: 75.0849, type: "domestic", passengers: 1000000, cargo: 1000, movements: 12000, runways: 1, longestRunwayFt: 8000, elevationFt: 1766, operator: "AAI", opened: 2003, airlines: ["IndiGo", "Air India", "SpiceJet"], topRoutes: ["BLR", "DEL", "BOM"], terminals: 1, parkingBays: 4, fuelType: "Jet A-1", avgDailyFlights: 28, internationalShare: 0, cargoShare: 0, hubFor: [], notables: "North Karnataka's main airport." },
  { iata: "IXG", icao: "VABM", name: "Belgaum Airport (Sambre)", city: "Belgaum", state: "Karnataka", lat: 15.8593, lon: 74.6183, type: "domestic", passengers: 200000, cargo: 0, movements: 3000, runways: 1, longestRunwayFt: 7500, elevationFt: 2487, operator: "AAI", opened: 2000, airlines: ["IndiGo", "SpiceJet"], topRoutes: ["BLR", "BOM", "DEL"], terminals: 1, parkingBays: 2, fuelType: "Jet A-1", avgDailyFlights: 8, internationalShare: 0, cargoShare: 0, hubFor: [], notables: "Karnataka border. New T1 2023." },
  { iata: "KLH", icao: "VAKP", name: "Kolhapur Airport", city: "Kolhapur", state: "Maharashtra", lat: 16.6645, lon: 74.2894, type: "domestic", passengers: 200000, cargo: 0, movements: 3000, runways: 1, longestRunwayFt: 5500, elevationFt: 1857, operator: "AAI", opened: 2017, airlines: ["IndiGo", "SpiceJet"], topRoutes: ["BOM", "BLR", "DEL"], terminals: 1, parkingBays: 2, fuelType: "Jet A-1", avgDailyFlights: 6, internationalShare: 0, cargoShare: 0, hubFor: [], notables: "New airport 2017. Mahalaxmi shrine." },
  { iata: "SSE", icao: "VASL", name: "Shirdi Airport (Kakad)", city: "Shirdi", state: "Maharashtra", lat: 19.6886, lon: 74.3789, type: "domestic", passengers: 300000, cargo: 0, movements: 5000, runways: 1, longestRunwayFt: 8200, elevationFt: 1926, operator: "MADC / AAI", opened: 2017, airlines: ["IndiGo", "SpiceJet", "Air India"], topRoutes: ["BOM", "DEL", "HYD"], terminals: 1, parkingBays: 3, fuelType: "Jet A-1", avgDailyFlights: 10, internationalShare: 0, cargoShare: 0, hubFor: [], notables: "Sai Baba shrine pilgrimage traffic." },
  { iata: "ISK", icao: "VANM", name: "Nashik Airport (Gandhinagar)", city: "Nashik", state: "Maharashtra", lat: 19.9633, lon: 73.8073, type: "domestic", passengers: 200000, cargo: 0, movements: 2500, runways: 1, longestRunwayFt: 6500, elevationFt: 1900, operator: "AAI", opened: 2023, airlines: ["IndiGo"], topRoutes: ["BOM"], terminals: 1, parkingBays: 2, fuelType: "Jet A-1", avgDailyFlights: 6, internationalShare: 0, cargoShare: 0, hubFor: [], notables: "Wine tourism. HAL-built." },
  { iata: "UDR", icao: "VAUD", name: "Maharana Pratap Airport", city: "Udaipur", state: "Rajasthan", lat: 24.6177, lon: 73.8961, type: "domestic", passengers: 1500000, cargo: 1000, movements: 15000, runways: 1, longestRunwayFt: 9000, elevationFt: 1693, operator: "AAI", opened: 1957, airlines: ["IndiGo", "Air India", "SpiceJet", "Vistara"], topRoutes: ["DEL", "BOM", "JAI", "BLR", "MAA"], terminals: 1, parkingBays: 5, fuelType: "Jet A-1", avgDailyFlights: 40, internationalShare: 3, cargoShare: 0, hubFor: [], notables: "City of Lakes. Heritage tourism." },
  { iata: "JDH", icao: "VIJO", name: "Jodhpur Airport", city: "Jodhpur", state: "Rajasthan", lat: 26.2511, lon: 73.0489, type: "domestic", passengers: 800000, cargo: 500, movements: 10000, runways: 1, longestRunwayFt: 9000, elevationFt: 717, operator: "AAI / Indian Air Force", opened: 1952, airlines: ["IndiGo", "Air India", "SpiceJet"], topRoutes: ["DEL", "BOM", "JAI", "BLR"], terminals: 1, parkingBays: 4, fuelType: "Jet A-1", avgDailyFlights: 22, internationalShare: 0, cargoShare: 0, hubFor: [], notables: "Blue City. Major IAF base." },
  { iata: "JSA", icao: "VISH", name: "Jaisalmer Airport", city: "Jaisalmer", state: "Rajasthan", lat: 26.8872, lon: 70.8668, type: "domestic", passengers: 200000, cargo: 0, movements: 3000, runways: 1, longestRunwayFt: 9000, elevationFt: 738, operator: "AAI", opened: 2017, airlines: ["SpiceJet", "IndiGo"], topRoutes: ["DEL", "JAI", "BOM"], terminals: 1, parkingBays: 2, fuelType: "Jet A-1", avgDailyFlights: 5, internationalShare: 0, cargoShare: 0, hubFor: [], notables: "Desert tourism. IAF exercises." },
  { iata: "BKB", icao: "VIBK", name: "Nal Airport (Bikaner)", city: "Bikaner", state: "Rajasthan", lat: 28.0706, lon: 73.2072, type: "domestic", passengers: 200000, cargo: 0, movements: 3000, runways: 1, longestRunwayFt: 9000, elevationFt: 765, operator: "Indian Air Force / AAI", opened: 1965, airlines: ["SpiceJet"], topRoutes: ["DEL", "JAI", "BOM"], terminals: 1, parkingBays: 2, fuelType: "Jet A-1", avgDailyFlights: 5, internationalShare: 0, cargoShare: 0, hubFor: [], notables: "Joint civil-military. Desert region." },
  { iata: "KQH", icao: "VIKG", name: "Kishangarh Airport", city: "Kishangarh", state: "Rajasthan", lat: 26.6014, lon: 74.8142, type: "domestic", passengers: 200000, cargo: 0, movements: 3000, runways: 1, longestRunwayFt: 6562, elevationFt: 1390, operator: "AAI", opened: 2017, airlines: ["IndiGo", "Star Air"], topRoutes: ["AMD", "DEL", "HDO", "LKO", "NAG", "PNQ"], terminals: 1, parkingBays: 2, fuelType: "Jet A-1", avgDailyFlights: 6, internationalShare: 0, cargoShare: 0, hubFor: [], notables: "Ajmer-Pushkar. Bani Thani painting inspired terminal." },
  { iata: "KTA", icao: "VAKT", name: "Kota Airport", city: "Kota", state: "Rajasthan", lat: 25.15, lon: 75.85, type: "domestic", passengers: 50000, cargo: 0, movements: 800, runways: 1, longestRunwayFt: 5000, elevationFt: 830, operator: "AAI", opened: 2020, airlines: ["SpiceJet"], topRoutes: ["DEL", "JAI"], terminals: 1, parkingBays: 2, fuelType: "Jet A-1", avgDailyFlights: 2, internationalShare: 0, cargoShare: 0, hubFor: [], notables: "Coaching hub. UDAN." },
  { iata: "GOP", icao: "VEGK", name: "Gorakhpur Airport", city: "Gorakhpur", state: "Uttar Pradesh", lat: 26.7397, lon: 83.4494, type: "domestic", passengers: 600000, cargo: 0, movements: 8000, runways: 1, longestRunwayFt: 9000, elevationFt: 259, operator: "AAI", opened: 1988, airlines: ["IndiGo", "SpiceJet", "Air India"], topRoutes: ["DEL", "BOM", "CCU"], terminals: 1, parkingBays: 4, fuelType: "Jet A-1", avgDailyFlights: 18, internationalShare: 0, cargoShare: 0, hubFor: [], notables: "UP's eastern gateway. Hindu pilgrim traffic." },
  { iata: "KNU", icao: "VIMP", name: "Kanpur Airport (Chakeri)", city: "Kanpur", state: "Uttar Pradesh", lat: 26.4045, lon: 80.3615, type: "domestic", passengers: 200000, cargo: 0, movements: 2500, runways: 1, longestRunwayFt: 8000, elevationFt: 482, operator: "Indian Air Force / AAI", opened: 1970, airlines: ["IndiGo", "SpiceJet"], topRoutes: ["DEL", "BOM"], terminals: 1, parkingBays: 2, fuelType: "Jet A-1", avgDailyFlights: 6, internationalShare: 0, cargoShare: 0, hubFor: [], notables: "Joint civil-military. New T1 2023." },
  { iata: "IXD", icao: "VIAL", name: "Prayagraj Airport (Bamrauli)", city: "Prayagraj", state: "Uttar Pradesh", lat: 25.4401, lon: 81.7339, type: "domestic", passengers: 400000, cargo: 0, movements: 6000, runways: 1, longestRunwayFt: 8000, elevationFt: 322, operator: "Indian Air Force / AAI", opened: 1966, airlines: ["IndiGo", "SpiceJet"], topRoutes: ["DEL", "BOM", "CCU"], terminals: 1, parkingBays: 3, fuelType: "Jet A-1", avgDailyFlights: 12, internationalShare: 0, cargoShare: 0, hubFor: [], notables: "Triveni Sangam (Kumbh Mela) city. IAF." },
  { iata: "HDO", icao: "VIHX", name: "Hindon Airport", city: "Ghaziabad", state: "Uttar Pradesh", lat: 28.8366, lon: 77.6544, type: "domestic", passengers: 300000, cargo: 0, movements: 4000, runways: 1, longestRunwayFt: 9000, elevationFt: 700, operator: "Indian Air Force", opened: 1930, airlines: ["IndiGo", "SpiceJet"], topRoutes: ["DEL", "PAT", "VNS"], terminals: 1, parkingBays: 3, fuelType: "Jet A-1", avgDailyFlights: 8, internationalShare: 0, cargoShare: 0, hubFor: [], notables: "Civil terminal opened 2019 at IAF base." },
  { iata: "DBR", icao: "VEDB", name: "Darbhanga Airport", city: "Darbhanga", state: "Bihar", lat: 26.1113, lon: 85.9847, type: "domestic", passengers: 500000, cargo: 0, movements: 8000, runways: 1, longestRunwayFt: 9000, elevationFt: 170, operator: "AAI", opened: 2020, airlines: ["IndiGo", "SpiceJet", "GoFirst"], topRoutes: ["DEL", "BOM", "CCU", "PAT"], terminals: 1, parkingBays: 4, fuelType: "Jet A-1", avgDailyFlights: 15, internationalShare: 0, cargoShare: 0, hubFor: [], notables: "New airport opened Nov 2020. UDAN." },
  { iata: "DIB", icao: "VEMN", name: "Dibrugarh Airport (Mohanbari)", city: "Dibrugarh", state: "Assam", lat: 27.4839, lon: 95.0169, type: "domestic", passengers: 700000, cargo: 500, movements: 10000, runways: 1, longestRunwayFt: 6000, elevationFt: 362, operator: "AAI", opened: 1952, airlines: ["IndiGo", "Air India", "SpiceJet"], topRoutes: ["DEL", "BOM", "CCU", "GAU"], terminals: 1, parkingBays: 5, fuelType: "Jet A-1", avgDailyFlights: 22, internationalShare: 0, cargoShare: 0, hubFor: [], notables: "Upper Assam. Oil & tea region gateway." },
  { iata: "JRH", icao: "VEJO", name: "Jorhat Airport (Rowriah)", city: "Jorhat", state: "Assam", lat: 26.7315, lon: 94.1756, type: "domestic", passengers: 300000, cargo: 0, movements: 5000, runways: 1, longestRunwayFt: 6000, elevationFt: 311, operator: "AAI / IAF", opened: 1958, airlines: ["IndiGo", "SpiceJet"], topRoutes: ["DEL", "BOM", "CCU", "GAU", "DIB"], terminals: 1, parkingBays: 3, fuelType: "Jet A-1", avgDailyFlights: 10, internationalShare: 0, cargoShare: 0, hubFor: [], notables: "Major tea district. New T1 2023." },
  { iata: "IXS", icao: "VEKU", name: "Silchar Airport (Kumbhirgram)", city: "Silchar", state: "Assam", lat: 24.9129, lon: 92.9787, type: "domestic", passengers: 300000, cargo: 0, movements: 4000, runways: 1, longestRunwayFt: 7500, elevationFt: 352, operator: "AAI / IAF", opened: 2014, airlines: ["IndiGo", "SpiceJet"], topRoutes: ["GAU", "CCU", "DEL"], terminals: 1, parkingBays: 3, fuelType: "Jet A-1", avgDailyFlights: 10, internationalShare: 0, cargoShare: 0, hubFor: [], notables: "Barak Valley region. IAF." },
  { iata: "SHL", icao: "VEBI", name: "Shillong Airport (Umroi)", city: "Shillong", state: "Meghalaya", lat: 25.7036, lon: 91.9787, type: "domestic", passengers: 500000, cargo: 0, movements: 8000, runways: 1, longestRunwayFt: 6000, elevationFt: 3156, operator: "AAI", opened: 2010, airlines: ["IndiGo", "Air India", "SpiceJet"], topRoutes: ["DEL", "BOM", "CCU", "GAU", "IMF"], terminals: 1, parkingBays: 3, fuelType: "Jet A-1", avgDailyFlights: 15, internationalShare: 0, cargoShare: 0, hubFor: [], notables: "High-elevation Meghalaya airport." },
  { iata: "DMU", icao: "VEMR", name: "Dimapur Airport", city: "Dimapur", state: "Nagaland", lat: 25.8839, lon: 93.7711, type: "domestic", passengers: 800000, cargo: 0, movements: 10000, runways: 1, longestRunwayFt: 7500, elevationFt: 330, operator: "AAI", opened: 1963, airlines: ["IndiGo", "Air India", "SpiceJet"], topRoutes: ["DEL", "BOM", "CCU", "GAU", "IMF"], terminals: 1, parkingBays: 4, fuelType: "Jet A-1", avgDailyFlights: 25, internationalShare: 0, cargoShare: 0, hubFor: [], notables: "Only commercial airport in Nagaland." },
  { iata: "AJL", icao: "VELP", name: "Lengpui Airport", city: "Aizawl", state: "Mizoram", lat: 23.8403, lon: 92.6197, type: "domestic", passengers: 400000, cargo: 0, movements: 5000, runways: 1, longestRunwayFt: 7500, elevationFt: 1200, operator: "AAI", opened: 2000, airlines: ["IndiGo", "Air India", "SpiceJet"], topRoutes: ["DEL", "BOM", "CCU", "GAU", "IMF"], terminals: 1, parkingBays: 3, fuelType: "Jet A-1", avgDailyFlights: 12, internationalShare: 0, cargoShare: 0, hubFor: [], notables: "Mizoram state airport." },
  { iata: "KUU", icao: "VIBR", name: "Kullu-Manali Airport (Bhuntar)", city: "Kullu", state: "Himachal Pradesh", lat: 31.8767, lon: 77.1556, type: "domestic", passengers: 200000, cargo: 0, movements: 2500, runways: 1, longestRunwayFt: 6000, elevationFt: 3623, operator: "AAI", opened: 1962, airlines: ["IndiGo", "Air India", "SpiceJet"], topRoutes: ["DEL", "BOM", "JAI"], terminals: 1, parkingBays: 2, fuelType: "Jet A-1", avgDailyFlights: 6, internationalShare: 0, cargoShare: 0, hubFor: [], notables: "Gateway to Kullu-Manali tourist circuit." },
  { iata: "DHM", icao: "VIGM", name: "Gaggal Airport (Kangra-Dharamshala)", city: "Kangra", state: "Himachal Pradesh", lat: 32.1944, lon: 75.9528, type: "domestic", passengers: 200000, cargo: 0, movements: 2500, runways: 1, longestRunwayFt: 6000, elevationFt: 2585, operator: "AAI", opened: 1990, airlines: ["IndiGo", "Air India", "SpiceJet"], topRoutes: ["DEL", "BOM"], terminals: 1, parkingBays: 2, fuelType: "Jet A-1", avgDailyFlights: 6, internationalShare: 0, cargoShare: 0, hubFor: [], notables: "Kangra Valley and Dharamshala." },
  { iata: "SLV", icao: "VISM", name: "Shimla Airport (Jubbarhatti)", city: "Shimla", state: "Himachal Pradesh", lat: 31.0788, lon: 77.0689, type: "domestic", passengers: 100000, cargo: 0, movements: 1500, runways: 1, longestRunwayFt: 5000, elevationFt: 5065, operator: "AAI", opened: 2010, airlines: ["Alliance Air"], topRoutes: ["DEL"], terminals: 1, parkingBays: 2, fuelType: "Jet A-1", avgDailyFlights: 2, internationalShare: 0, cargoShare: 0, hubFor: [], notables: "High-altitude airport. Limited ATR ops." },
  { iata: "PGH", icao: "VIPT", name: "Pantnagar Airport", city: "Pantnagar", state: "Uttarakhand", lat: 29.0337, lon: 79.4736, type: "domestic", passengers: 200000, cargo: 0, movements: 2500, runways: 1, longestRunwayFt: 6500, elevationFt: 769, operator: "AAI", opened: 1980, airlines: ["IndiGo", "SpiceJet"], topRoutes: ["DEL", "BOM"], terminals: 1, parkingBays: 2, fuelType: "Jet A-1", avgDailyFlights: 6, internationalShare: 0, cargoShare: 0, hubFor: [], notables: "Kumaon. Industrial city." },
  { iata: "BUP", icao: "VIBT", name: "Bhatinda Airport (Bhisiana)", city: "Bathinda", state: "Punjab", lat: 30.2701, lon: 74.7557, type: "domestic", passengers: 100000, cargo: 0, movements: 1500, runways: 1, longestRunwayFt: 9000, elevationFt: 662, operator: "Indian Air Force / AAI", opened: 2000, airlines: ["SpiceJet"], topRoutes: ["DEL", "JAI"], terminals: 1, parkingBays: 2, fuelType: "Jet A-1", avgDailyFlights: 3, internationalShare: 0, cargoShare: 0, hubFor: [], notables: "Punjab IAF base. Cotton belt." },
  { iata: "LUH", icao: "VILD", name: "Ludhiana Airport (Sahnewal)", city: "Ludhiana", state: "Punjab", lat: 30.8547, lon: 75.9522, type: "domestic", passengers: 200000, cargo: 0, movements: 3000, runways: 1, longestRunwayFt: 6000, elevationFt: 834, operator: "AAI", opened: 1990, airlines: ["IndiGo", "SpiceJet"], topRoutes: ["DEL", "JAI", "BOM"], terminals: 1, parkingBays: 2, fuelType: "Jet A-1", avgDailyFlights: 6, internationalShare: 0, cargoShare: 0, hubFor: [], notables: "Punjab's largest city. Industrial." },
  { iata: "IXP", icao: "VIPK", name: "Pathankot Airport (Civil)", city: "Pathankot", state: "Punjab", lat: 32.2341, lon: 75.6344, type: "domestic", passengers: 50000, cargo: 0, movements: 800, runways: 1, longestRunwayFt: 9000, elevationFt: 1017, operator: "Indian Air Force / AAI", opened: 2018, airlines: ["SpiceJet"], topRoutes: ["DEL"], terminals: 1, parkingBays: 2, fuelType: "Jet A-1", avgDailyFlights: 2, internationalShare: 0, cargoShare: 0, hubFor: [], notables: "Civil terminal at IAF base. Pakistan border." },
  { iata: "BHJ", icao: "VABV", name: "Bhuj Airport (Rudra Mata)", city: "Bhuj", state: "Gujarat", lat: 23.2879, lon: 69.6707, type: "domestic", passengers: 200000, cargo: 0, movements: 3000, runways: 1, longestRunwayFt: 8000, elevationFt: 248, operator: "Indian Air Force / AAI", opened: 2000, airlines: ["SpiceJet"], topRoutes: ["DEL", "BOM", "AMD"], terminals: 1, parkingBays: 2, fuelType: "Jet A-1", avgDailyFlights: 6, internationalShare: 0, cargoShare: 0, hubFor: [], notables: "Joint civil-military. Pakistan border." },
  { iata: "BWR", icao: "VABW", name: "Bhavnagar Airport", city: "Bhavnagar", state: "Gujarat", lat: 21.7522, lon: 72.1853, type: "domestic", passengers: 200000, cargo: 0, movements: 3000, runways: 1, longestRunwayFt: 6500, elevationFt: 34, operator: "AAI", opened: 2000, airlines: ["IndiGo", "SpiceJet"], topRoutes: ["BOM", "AMD", "DEL"], terminals: 1, parkingBays: 2, fuelType: "Jet A-1", avgDailyFlights: 6, internationalShare: 0, cargoShare: 0, hubFor: [], notables: "Gujarat industrial port city." },
  { iata: "JGA", icao: "VAJM", name: "Jamnagar Airport", city: "Jamnagar", state: "Gujarat", lat: 22.4655, lon: 70.0725, type: "domestic", passengers: 300000, cargo: 2000, movements: 4000, runways: 1, longestRunwayFt: 8240, elevationFt: 69, operator: "Indian Air Force / AAI", opened: 1960, airlines: ["IndiGo", "SpiceJet"], topRoutes: ["BOM", "AMD", "DEL"], terminals: 1, parkingBays: 3, fuelType: "Jet A-1", avgDailyFlights: 10, internationalShare: 0, cargoShare: 0, hubFor: [], notables: "IAF base. Reliance refinery traffic." },
  { iata: "HSR", icao: "VAHS", name: "Rajkot International Airport (Hirasar)", city: "Rajkot", state: "Gujarat", lat: 22.3881, lon: 71.0283, type: "international", passengers: 1088570, cargo: 608, movements: 8294, runways: 1, longestRunwayFt: 10000, elevationFt: 580, operator: "AAI", opened: 2023, airlines: ["IndiGo", "Air India"], topRoutes: ["DEL", "BOM", "BLR", "HYD", "NMI", "PNQ"], terminals: 1, parkingBays: 14, fuelType: "Jet A-1", avgDailyFlights: 35, internationalShare: 0, cargoShare: 0, hubFor: [], notables: "New greenfield international airport at Hirasar. Opened Sept 2023. Replaced old Rajkot." },
  { iata: "RAJ", icao: "VARK", name: "Rajkot Airport (Old)", city: "Rajkot", state: "Gujarat", lat: 22.3033, lon: 70.7794, type: "domestic", passengers: 0, cargo: 0, movements: 0, runways: 1, longestRunwayFt: 6000, elevationFt: 441, operator: "AAI", opened: 1937, airlines: [], topRoutes: [], terminals: 1, parkingBays: 4, fuelType: "Jet A-1", avgDailyFlights: 0, internationalShare: 0, cargoShare: 0, hubFor: [], notables: "Old Rajkot airport. Commercial ops shifted to Hirasar Sept 2023. Now VIP/general aviation only." },
  { iata: "BDQ", icao: "VABO", name: "Vadodara Airport (Harni)", city: "Vadodara", state: "Gujarat", lat: 22.3362, lon: 73.2263, type: "domestic", passengers: 1200000, cargo: 1500, movements: 12000, runways: 1, longestRunwayFt: 8000, elevationFt: 127, operator: "AAI", opened: 2016, airlines: ["IndiGo", "SpiceJet", "Air India"], topRoutes: ["DEL", "BOM", "AMD"], terminals: 1, parkingBays: 4, fuelType: "Jet A-1", avgDailyFlights: 33, internationalShare: 0, cargoShare: 0, hubFor: [], notables: "New T1 2016. Industrial Gujarat." },
  { iata: "PBD", icao: "VAPR", name: "Porbandar Airport", city: "Porbandar", state: "Gujarat", lat: 21.6487, lon: 69.6572, type: "domestic", passengers: 50000, cargo: 0, movements: 800, runways: 1, longestRunwayFt: 5000, elevationFt: 23, operator: "AAI", opened: 2000, airlines: ["SpiceJet"], topRoutes: ["BOM", "AMD"], terminals: 1, parkingBays: 2, fuelType: "Jet A-1", avgDailyFlights: 2, internationalShare: 0, cargoShare: 0, hubFor: [], notables: "Gandhi birthplace. Limited ops." },
  { iata: "KEM", icao: "VAKS", name: "Keshod Airport", city: "Keshod", state: "Gujarat", lat: 21.3167, lon: 70.2683, type: "domestic", passengers: 10000, cargo: 0, movements: 300, runways: 1, longestRunwayFt: 4500, elevationFt: 167, operator: "AAI", opened: 2023, airlines: ["SpiceJet"], topRoutes: ["BOM"], terminals: 1, parkingBays: 2, fuelType: "Jet A-1", avgDailyFlights: 1, internationalShare: 0, cargoShare: 0, hubFor: [], notables: "Saurashtra region. UDAN. Opened 2023." },
  { iata: "JLR", icao: "VAJB", name: "Jabalpur Airport (Dumna)", city: "Jabalpur", state: "Madhya Pradesh", lat: 23.1778, lon: 80.0522, type: "domestic", passengers: 300000, cargo: 0, movements: 5000, runways: 1, longestRunwayFt: 6900, elevationFt: 1624, operator: "AAI", opened: 1946, airlines: ["IndiGo", "Air India", "SpiceJet"], topRoutes: ["DEL", "BOM", "HYD"], terminals: 1, parkingBays: 3, fuelType: "Jet A-1", avgDailyFlights: 10, internationalShare: 0, cargoShare: 0, hubFor: [], notables: "Marble City. Khajuraho nearby." },
  { iata: "GWL", icao: "VIGR", name: "Gwalior Airport (Maharajpura)", city: "Gwalior", state: "Madhya Pradesh", lat: 26.2933, lon: 78.2278, type: "domestic", passengers: 500000, cargo: 0, movements: 8000, runways: 1, longestRunwayFt: 9000, elevationFt: 617, operator: "Indian Air Force / AAI", opened: 1937, airlines: ["IndiGo", "SpiceJet"], topRoutes: ["DEL", "BOM", "JAI"], terminals: 1, parkingBays: 4, fuelType: "Jet A-1", avgDailyFlights: 15, internationalShare: 0, cargoShare: 0, hubFor: [], notables: "Joint civil-military. Largest IAF base." },
  { iata: "HJR", icao: "VAKJ", name: "Khajuraho Airport", city: "Khajuraho", state: "Madhya Pradesh", lat: 24.8172, lon: 79.9186, type: "domestic", passengers: 100000, cargo: 0, movements: 1500, runways: 1, longestRunwayFt: 7000, elevationFt: 738, operator: "AAI", opened: 1983, airlines: ["SpiceJet", "IndiGo"], topRoutes: ["DEL", "BOM", "JAI", "VNS"], terminals: 1, parkingBays: 2, fuelType: "Jet A-1", avgDailyFlights: 3, internationalShare: 0, cargoShare: 0, hubFor: [], notables: "UNESCO World Heritage temples." },
  { iata: "TNI", icao: "VIST", name: "Satna Airport", city: "Satna", state: "Madhya Pradesh", lat: 24.5623, lon: 80.8593, type: "domestic", passengers: 50000, cargo: 0, movements: 800, runways: 1, longestRunwayFt: 5000, elevationFt: 1050, operator: "AAI", opened: 2022, airlines: ["SpiceJet"], topRoutes: ["DEL", "BOM"], terminals: 1, parkingBays: 2, fuelType: "Jet A-1", avgDailyFlights: 2, internationalShare: 0, cargoShare: 0, hubFor: [], notables: "New UDAN airport." },
  { iata: "JRG", icao: "VEJH", name: "Veer Surendra Sai Airport", city: "Jharsuguda", state: "Odisha", lat: 21.9133, lon: 84.0503, type: "domestic", passengers: 700000, cargo: 0, movements: 6000, runways: 1, longestRunwayFt: 8200, elevationFt: 720, operator: "AAI", opened: 2018, airlines: ["IndiGo", "Star Air"], topRoutes: ["DEL", "CCU", "BLR", "BOM", "NMI", "HYD"], terminals: 1, parkingBays: 4, fuelType: "Jet A-1", avgDailyFlights: 18, internationalShare: 0, cargoShare: 0, hubFor: [], notables: "Odisha's 2nd commercial airport. IndiGo & Star Air flights." },
  { iata: "PYB", icao: "VOPJ", name: "Jeypore Airport", city: "Jeypore", state: "Odisha", lat: 18.8803, lon: 82.5525, type: "domestic", passengers: 50000, cargo: 0, movements: 800, runways: 1, longestRunwayFt: 5000, elevationFt: 1000, operator: "AAI", opened: 2022, airlines: ["SpiceJet"], topRoutes: ["BBI", "HYD"], terminals: 1, parkingBays: 2, fuelType: "Jet A-1", avgDailyFlights: 2, internationalShare: 0, cargoShare: 0, hubFor: [], notables: "Newest airport in Odisha. Under UDAN." },
  { iata: "NAG", icao: "VAND", name: "Nashik Airport (Ozar)", city: "Nashik", state: "Maharashtra", lat: 20.1189, lon: 73.9128, type: "domestic", passengers: 200000, cargo: 0, movements: 2500, runways: 1, longestRunwayFt: 9000, elevationFt: 1900, operator: "HAL / AAI", opened: 2007, airlines: ["IndiGo", "SpiceJet"], topRoutes: ["BOM", "DEL", "BLR"], terminals: 1, parkingBays: 2, fuelType: "Jet A-1", avgDailyFlights: 6, internationalShare: 0, cargoShare: 0, hubFor: [], notables: "Wine tourism. HAL-built." },
  { iata: "NDC", icao: "VAND", name: "Nanded Airport (Shri Guru Gobind Singh Ji)", city: "Nanded", state: "Maharashtra", lat: 19.1822, lon: 77.3225, type: "domestic", passengers: 50000, cargo: 0, movements: 1000, runways: 1, longestRunwayFt: 6000, elevationFt: 1224, operator: "AAI", opened: 2017, airlines: ["SpiceJet"], topRoutes: ["BOM", "HYD"], terminals: 1, parkingBays: 2, fuelType: "Jet A-1", avgDailyFlights: 2, internationalShare: 0, cargoShare: 0, hubFor: [], notables: "Sikh pilgrimage. New T1 2024." },
  { iata: "IXZ", icao: "VOPB", name: "Veer Savarkar International Airport", city: "Port Blair", state: "Andaman & Nicobar", lat: 11.6412, lon: 92.7297, type: "domestic", passengers: 1200000, cargo: 200, movements: 15000, runways: 1, longestRunwayFt: 10700, elevationFt: 14, operator: "AAI", opened: 1958, airlines: ["IndiGo", "Air India", "SpiceJet", "GoFirst", "Vistara"], topRoutes: ["DEL", "BOM", "CCU", "BLR", "MAA"], terminals: 1, parkingBays: 6, fuelType: "Jet A-1", avgDailyFlights: 40, internationalShare: 0, cargoShare: 0, hubFor: [], notables: "Gateway to Andaman & Nicobar Islands." },
  { iata: "AGX", icao: "VOAT", name: "Agatti Airport", city: "Agatti", state: "Lakshadweep", lat: 10.8237, lon: 72.1761, type: "domestic", passengers: 50000, cargo: 0, movements: 800, runways: 1, longestRunwayFt: 4000, elevationFt: 14, operator: "AAI", opened: 1987, airlines: ["Air India"], topRoutes: ["CCJ"], terminals: 1, parkingBays: 1, fuelType: "Jet A-1", avgDailyFlights: 2, internationalShare: 0, cargoShare: 0, hubFor: [], notables: "Only commercial airport in Lakshadweep. STOL-capable." },
  { iata: "NMB", icao: "VADN", name: "Daman Airport", city: "Daman", state: "Dadra and Nagar Haveli and Daman and Diu", lat: 20.4344, lon: 72.8433, type: "domestic", passengers: 100000, cargo: 0, movements: 1500, runways: 1, longestRunwayFt: 6000, elevationFt: 33, operator: "AAI", opened: 1964, airlines: ["SpiceJet"], topRoutes: ["DEL", "BOM"], terminals: 1, parkingBays: 2, fuelType: "Jet A-1", avgDailyFlights: 3, internationalShare: 0, cargoShare: 0, hubFor: [], notables: "Daman UT. Seasonal charter traffic." },
  { iata: "PYK", icao: "VOPM", name: "Pondicherry Airport", city: "Puducherry", state: "Puducherry", lat: 11.9687, lon: 79.8106, type: "domestic", passengers: 100000, cargo: 0, movements: 1500, runways: 1, longestRunwayFt: 4500, elevationFt: 43, operator: "AAI", opened: 2000, airlines: ["SpiceJet"], topRoutes: ["MAA", "BLR", "HYD"], terminals: 1, parkingBays: 2, fuelType: "Jet A-1", avgDailyFlights: 3, internationalShare: 0, cargoShare: 0, hubFor: [], notables: "French colonial UT. Limited." },
  { iata: "KVR", icao: "VAKV", name: "Kavaratti Airport", city: "Kavaratti", state: "Lakshadweep", lat: 10.55, lon: 72.6333, type: "domestic", passengers: 20000, cargo: 0, movements: 400, runways: 1, longestRunwayFt: 3500, elevationFt: 10, operator: "AAI", opened: 1988, airlines: ["Air India"], topRoutes: ["CCJ", "AGX"], terminals: 1, parkingBays: 1, fuelType: "Jet A-1", avgDailyFlights: 1, internationalShare: 0, cargoShare: 0, hubFor: [], notables: "Lakshadweep capital. Helicopter ops." },
  { iata: "JAG", icao: "VAJP", name: "Jagdalpur Airport (Maa Danteshwari)", city: "Jagdalpur", state: "Chhattisgarh", lat: 19.0736, lon: 82.0384, type: "domestic", passengers: 50000, cargo: 0, movements: 800, runways: 1, longestRunwayFt: 5000, elevationFt: 1500, operator: "AAI", opened: 2022, airlines: ["IndiGo"], topRoutes: ["RPR", "DEL"], terminals: 1, parkingBays: 2, fuelType: "Jet A-1", avgDailyFlights: 2, internationalShare: 0, cargoShare: 0, hubFor: [], notables: "Newest airport in Chhattisgarh. Bastar region." },
  { iata: "PAB", icao: "VIBP", name: "Bilaspur Airport", city: "Bilaspur", state: "Chhattisgarh", lat: 21.9884, lon: 82.111, type: "domestic", passengers: 100000, cargo: 0, movements: 1500, runways: 1, longestRunwayFt: 6000, elevationFt: 899, operator: "AAI", opened: 2021, airlines: ["IndiGo", "SpiceJet"], topRoutes: ["DEL", "RPR", "BOM"], terminals: 1, parkingBays: 2, fuelType: "Jet A-1", avgDailyFlights: 3, internationalShare: 0, cargoShare: 0, hubFor: [], notables: "New UDAN airport." },
  { iata: "CDP", icao: "VOCP", name: "Cuddapah Airport", city: "Kadapa", state: "Andhra Pradesh", lat: 14.51, lon: 78.7728, type: "domestic", passengers: 200000, cargo: 0, movements: 3000, runways: 1, longestRunwayFt: 7500, elevationFt: 433, operator: "AAI", opened: 2000, airlines: ["IndiGo", "SpiceJet"], topRoutes: ["HYD", "DEL", "BOM"], terminals: 1, parkingBays: 2, fuelType: "Jet A-1", avgDailyFlights: 6, internationalShare: 0, cargoShare: 0, hubFor: [], notables: "Rayalaseema region." },
  { iata: "KMW", icao: "VOKM", name: "Kurnool Airport (Orvakal)", city: "Kurnool", state: "Andhra Pradesh", lat: 15.75, lon: 78.1, type: "domestic", passengers: 200000, cargo: 0, movements: 3000, runways: 1, longestRunwayFt: 6500, elevationFt: 920, operator: "AAI", opened: 2020, airlines: ["IndiGo", "SpiceJet"], topRoutes: ["HYD", "DEL", "BLR"], terminals: 1, parkingBays: 2, fuelType: "Jet A-1", avgDailyFlights: 8, internationalShare: 0, cargoShare: 0, hubFor: [], notables: "AP's 5th operational." },
  { iata: "RJA", icao: "VORY", name: "Rajahmundry Airport", city: "Rajahmundry", state: "Andhra Pradesh", lat: 17.1104, lon: 81.8182, type: "domestic", passengers: 500000, cargo: 0, movements: 6000, runways: 1, longestRunwayFt: 6000, elevationFt: 151, operator: "AAI", opened: 1977, airlines: ["IndiGo", "SpiceJet"], topRoutes: ["HYD", "BOM", "DEL"], terminals: 1, parkingBays: 3, fuelType: "Jet A-1", avgDailyFlights: 15, internationalShare: 0, cargoShare: 0, hubFor: [], notables: "Godavari region. New T1 2024." },
  { iata: "TCR", icao: "VOTK", name: "Tuticorin Airport (Vagaikulam)", city: "Thoothukudi", state: "Tamil Nadu", lat: 8.7242, lon: 78.0258, type: "domestic", passengers: 300000, cargo: 0, movements: 4000, runways: 1, longestRunwayFt: 6500, elevationFt: 129, operator: "AAI", opened: 2018, airlines: ["IndiGo", "SpiceJet"], topRoutes: ["MAA", "BLR", "DEL"], terminals: 1, parkingBays: 3, fuelType: "Jet A-1", avgDailyFlights: 8, internationalShare: 0, cargoShare: 0, hubFor: [], notables: "Tuticorin port gateway." },
  { iata: "SRM", icao: "VOSM", name: "Salem Airport", city: "Salem", state: "Tamil Nadu", lat: 11.7833, lon: 78.0656, type: "domestic", passengers: 50000, cargo: 0, movements: 800, runways: 1, longestRunwayFt: 6000, elevationFt: 991, operator: "AAI", opened: 2010, airlines: ["SpiceJet"], topRoutes: ["MAA", "BLR"], terminals: 1, parkingBays: 2, fuelType: "Jet A-1", avgDailyFlights: 2, internationalShare: 0, cargoShare: 0, hubFor: [], notables: "Steel city. Limited ops." },
  { iata: "MYQ", icao: "VOMY", name: "Mysore Airport (Mandakalli)", city: "Mysuru", state: "Karnataka", lat: 12.23, lon: 76.65, type: "domestic", passengers: 200000, cargo: 0, movements: 3000, runways: 1, longestRunwayFt: 7000, elevationFt: 2349, operator: "AAI", opened: 2010, airlines: ["IndiGo", "SpiceJet"], topRoutes: ["BLR", "HYD", "DEL"], terminals: 1, parkingBays: 2, fuelType: "Jet A-1", avgDailyFlights: 6, internationalShare: 0, cargoShare: 0, hubFor: [], notables: "Heritage city. Limited." },
  { iata: "SHM", icao: "VOSH", name: "Shimoga Airport (Shivamogga)", city: "Shimoga", state: "Karnataka", lat: 13.9333, lon: 75.5667, type: "domestic", passengers: 50000, cargo: 0, movements: 800, runways: 1, longestRunwayFt: 5500, elevationFt: 1900, operator: "AAI", opened: 2020, airlines: ["SpiceJet"], topRoutes: ["BLR", "DEL"], terminals: 1, parkingBays: 2, fuelType: "Jet A-1", avgDailyFlights: 2, internationalShare: 0, cargoShare: 0, hubFor: [], notables: "Malnad region. UDAN." },
  { iata: "IXI", icao: "VELR", name: "Lilabari Airport", city: "North Lakhimpur", state: "Assam", lat: 27.2928, lon: 94.0976, type: "domestic", passengers: 100000, cargo: 0, movements: 1500, runways: 1, longestRunwayFt: 6000, elevationFt: 330, operator: "AAI", opened: 2000, airlines: ["IndiGo", "SpiceJet"], topRoutes: ["GAU", "CCU", "DEL"], terminals: 1, parkingBays: 2, fuelType: "Jet A-1", avgDailyFlights: 3, internationalShare: 0, cargoShare: 0, hubFor: [], notables: "Upper Assam gateway." },
  { iata: "TEZ", icao: "VETZ", name: "Tezpur Airport", city: "Tezpur", state: "Assam", lat: 26.7091, lon: 92.7842, type: "domestic", passengers: 100000, cargo: 0, movements: 1500, runways: 1, longestRunwayFt: 6000, elevationFt: 240, operator: "Indian Air Force", opened: 1960, airlines: ["IndiGo", "SpiceJet"], topRoutes: ["GAU", "CCU", "DEL"], terminals: 1, parkingBays: 2, fuelType: "Jet A-1", avgDailyFlights: 3, internationalShare: 0, cargoShare: 0, hubFor: [], notables: "IAF base opened for commercial use." },
  { iata: "AYJ", icao: "VEAN", name: "Itanagar Airport (Hollongi)", city: "Itanagar", state: "Arunachal Pradesh", lat: 26.9311, lon: 93.6425, type: "domestic", passengers: 200000, cargo: 0, movements: 3000, runways: 1, longestRunwayFt: 7800, elevationFt: 330, operator: "AAI", opened: 2022, airlines: ["IndiGo", "Alliance Air"], topRoutes: ["DEL", "GAU", "CCU"], terminals: 1, parkingBays: 3, fuelType: "Jet A-1", avgDailyFlights: 8, internationalShare: 0, cargoShare: 0, hubFor: [], notables: "Newest AP airport, opened Nov 2022." },
  { iata: "ZER", icao: "VEZO", name: "Zero Airport", city: "Zero", state: "Arunachal Pradesh", lat: 27.5883, lon: 93.8476, type: "domestic", passengers: 20000, cargo: 0, movements: 400, runways: 1, longestRunwayFt: 4000, elevationFt: 5000, operator: "AAI", opened: 2020, airlines: ["Alliance Air"], topRoutes: ["DIB", "GAU"], terminals: 1, parkingBays: 1, fuelType: "Jet A-1", avgDailyFlights: 1, internationalShare: 0, cargoShare: 0, hubFor: [], notables: "Arunachal Pradesh remote. Highest state." },
  { iata: "DTE", icao: "VEDT", name: "Daporijo Airport", city: "Daporijo", state: "Arunachal Pradesh", lat: 27.9833, lon: 94.2333, type: "domestic", passengers: 10000, cargo: 0, movements: 300, runways: 1, longestRunwayFt: 4000, elevationFt: 3000, operator: "AAI", opened: 2020, airlines: ["Alliance Air"], topRoutes: ["DIB", "GAU"], terminals: 1, parkingBays: 1, fuelType: "Jet A-1", avgDailyFlights: 1, internationalShare: 0, cargoShare: 0, hubFor: [], notables: "Arunachal Pradesh remote. ALH heli-ops." },
  { iata: "TJV", icao: "VETJ", name: "Tezu Airport", city: "Tezu", state: "Arunachal Pradesh", lat: 27.9417, lon: 96.1344, type: "domestic", passengers: 15000, cargo: 0, movements: 400, runways: 1, longestRunwayFt: 4000, elevationFt: 1500, operator: "AAI", opened: 2020, airlines: ["Alliance Air"], topRoutes: ["DIB", "GAU"], terminals: 1, parkingBays: 1, fuelType: "Jet A-1", avgDailyFlights: 1, internationalShare: 0, cargoShare: 0, hubFor: [], notables: "Arunachal Pradesh eastern. ALH." },
  { iata: "PYG", icao: "VEPY", name: "Pakyong Airport", city: "Gangtok", state: "Sikkim", lat: 27.2317, lon: 88.5875, type: "domestic", passengers: 200000, cargo: 0, movements: 3000, runways: 1, longestRunwayFt: 7200, elevationFt: 4642, operator: "AAI", opened: 2018, airlines: ["SpiceJet", "IndiGo"], topRoutes: ["DEL", "CCU", "BLR"], terminals: 1, parkingBays: 3, fuelType: "Jet A-1", avgDailyFlights: 8, internationalShare: 0, cargoShare: 0, hubFor: [], notables: "Sikkim's only airport. India's 100th operational." },
  { iata: "MZU", icao: "VEMZ", name: "Muzaffarpur Airport", city: "Muzaffarpur", state: "Bihar", lat: 26.1161, lon: 85.3136, type: "domestic", passengers: 50000, cargo: 0, movements: 800, runways: 1, longestRunwayFt: 5000, elevationFt: 170, operator: "AAI", opened: 2023, airlines: ["IndiGo"], topRoutes: ["DEL", "PAT"], terminals: 1, parkingBays: 2, fuelType: "Jet A-1", avgDailyFlights: 2, internationalShare: 0, cargoShare: 0, hubFor: [], notables: "Newest airport in Bihar. Under UDAN scheme." },
  { iata: "IXN", icao: "VEKW", name: "Khowai Airport", city: "Khowai", state: "Tripura", lat: 24.0667, lon: 91.6167, type: "domestic", passengers: 10000, cargo: 0, movements: 300, runways: 1, longestRunwayFt: 4000, elevationFt: 100, operator: "AAI", opened: 2021, airlines: ["Alliance Air"], topRoutes: ["IXA", "CCU", "GAU"], terminals: 1, parkingBays: 1, fuelType: "Jet A-1", avgDailyFlights: 1, internationalShare: 0, cargoShare: 0, hubFor: [], notables: "Tripura small airport. UDAN." },
  { iata: "KMR", icao: "VEKM", name: "Kamalpur Airport", city: "Kamalpur", state: "Tripura", lat: 24.1833, lon: 91.8, type: "domestic", passengers: 5000, cargo: 0, movements: 200, runways: 1, longestRunwayFt: 3500, elevationFt: 50, operator: "AAI", opened: 2022, airlines: ["Alliance Air"], topRoutes: ["IXA", "CCU"], terminals: 1, parkingBays: 1, fuelType: "Jet A-1", avgDailyFlights: 1, internationalShare: 0, cargoShare: 0, hubFor: [], notables: "Tripura 2nd. Smallest active." },
  { iata: "CBD", icao: "VECO", name: "Cooch Behar Airport", city: "Cooch Behar", state: "West Bengal", lat: 26.3333, lon: 89.4667, type: "domestic", passengers: 10000, cargo: 0, movements: 300, runways: 1, longestRunwayFt: 4000, elevationFt: 200, operator: "AAI", opened: 2021, airlines: ["Alliance Air"], topRoutes: ["CCU", "BBI", "GAU"], terminals: 1, parkingBays: 1, fuelType: "Jet A-1", avgDailyFlights: 1, internationalShare: 0, cargoShare: 0, hubFor: [], notables: "North Bengal. Heritage town." },
  { iata: "BXC", icao: "VEBA", name: "Balurghat Airport", city: "Balurghat", state: "West Bengal", lat: 25.25, lon: 88.7833, type: "domestic", passengers: 10000, cargo: 0, movements: 300, runways: 1, longestRunwayFt: 4000, elevationFt: 120, operator: "AAI", opened: 2022, airlines: ["Alliance Air"], topRoutes: ["CCU", "BBI"], terminals: 1, parkingBays: 1, fuelType: "Jet A-1", avgDailyFlights: 1, internationalShare: 0, cargoShare: 0, hubFor: [], notables: "South Dinajpur. UDAN." },
  { iata: "JPG", icao: "VIJN", name: "Jhansi Airport", city: "Jhansi", state: "Uttar Pradesh", lat: 25.3167, lon: 78.5833, type: "domestic", passengers: 50000, cargo: 0, movements: 800, runways: 1, longestRunwayFt: 5000, elevationFt: 800, operator: "AAI", opened: 2023, airlines: ["SpiceJet"], topRoutes: ["DEL"], terminals: 1, parkingBays: 2, fuelType: "Jet A-1", avgDailyFlights: 2, internationalShare: 0, cargoShare: 0, hubFor: [], notables: "New airport under UDAN scheme." },
  { iata: "HSS", icao: "VIHR", name: "Hissar Airport", city: "Hissar", state: "Haryana", lat: 29.1794, lon: 75.7553, type: "domestic", passengers: 50000, cargo: 0, movements: 1000, runways: 1, longestRunwayFt: 6000, elevationFt: 700, operator: "AAI", opened: 2020, airlines: ["SpiceJet"], topRoutes: ["DEL"], terminals: 1, parkingBays: 2, fuelType: "Jet A-1", avgDailyFlights: 2, internationalShare: 0, cargoShare: 0, hubFor: [], notables: "New airport under UDAN scheme." },
  { iata: "IXY", icao: "VAKD", name: "Kandla Airport", city: "Kandla", state: "Gujarat", lat: 23.1125, lon: 70.1003, type: "domestic", passengers: 100000, cargo: 0, movements: 2000, runways: 1, longestRunwayFt: 6000, elevationFt: 96, operator: "AAI", opened: 1964, airlines: ["SpiceJet"], topRoutes: ["AMD", "BOM", "DEL"], terminals: 1, parkingBays: 2, fuelType: "Jet A-1", avgDailyFlights: 4, internationalShare: 0, cargoShare: 0, hubFor: [], notables: "Deendayal Port gateway. Underutilized." },
  { iata: "JGA", icao: "VAJA", name: "Ahmedabad (Ref)", city: "Ahmedabad", state: "Gujarat", lat: 23.0773, lon: 72.6347, type: "international", passengers: 14000000, cargo: 90000, movements: 120000, runways: 2, longestRunwayFt: 11811, elevationFt: 189, operator: "Adani Group", opened: 1937, airlines: ["IndiGo", "Air India", "SpiceJet", "Vistara", "Akasa"], topRoutes: ["DEL", "BOM", "BLR", "MAA", "GOI"], terminals: 2, parkingBays: 42, fuelType: "Jet A-1", avgDailyFlights: 330, internationalShare: 4, cargoShare: 3, hubFor: ["IndiGo"], notables: "Same as AMD. Reference." },
  { iata: "SIV", icao: "VESS", name: "Sonari Airport (Sibsagar)", city: "Sibsagar", state: "Assam", lat: 26.9956, lon: 94.6394, type: "domestic", passengers: 50000, cargo: 0, movements: 800, runways: 1, longestRunwayFt: 5000, elevationFt: 300, operator: "AAI", opened: 2010, airlines: ["SpiceJet"], topRoutes: ["GAU", "CCU"], terminals: 1, parkingBays: 2, fuelType: "Jet A-1", avgDailyFlights: 2, internationalShare: 0, cargoShare: 0, hubFor: [], notables: "Small Assam airport. Limited ops." },
  { iata: "NNS", icao: "VINS", name: "Naini Saini Airport", city: "Pithoragarh", state: "Uttarakhand", lat: 29.5667, lon: 80.2333, type: "domestic", passengers: 20000, cargo: 0, movements: 400, runways: 1, longestRunwayFt: 4500, elevationFt: 4900, operator: "AAI", opened: 2022, airlines: ["Alliance Air"], topRoutes: ["DED", "DEL"], terminals: 1, parkingBays: 1, fuelType: "Jet A-1", avgDailyFlights: 1, internationalShare: 0, cargoShare: 0, hubFor: [], notables: "Kailash Mansarovar gateway. UDAN." },
  { iata: "WGC", icao: "VOWC", name: "Warangal Airport", city: "Warangal", state: "Telangana", lat: 17.9167, lon: 79.6, type: "domestic", passengers: 50000, cargo: 0, movements: 800, runways: 1, longestRunwayFt: 6000, elevationFt: 920, operator: "AAI", opened: 2020, airlines: ["SpiceJet"], topRoutes: ["HYD", "DEL"], terminals: 1, parkingBays: 2, fuelType: "Jet A-1", avgDailyFlights: 2, internationalShare: 0, cargoShare: 0, hubFor: [], notables: "Kakatiya heritage. UDAN." },
  { iata: "IXS", icao: "VOKU", name: "Silchar (Ref)", city: "Silchar", state: "Assam", lat: 24.9129, lon: 92.9787, type: "domestic", passengers: 300000, cargo: 0, movements: 4000, runways: 1, longestRunwayFt: 7500, elevationFt: 352, operator: "AAI / IAF", opened: 2014, airlines: ["IndiGo", "SpiceJet"], topRoutes: ["GAU", "CCU", "DEL"], terminals: 1, parkingBays: 3, fuelType: "Jet A-1", avgDailyFlights: 10, internationalShare: 0, cargoShare: 0, hubFor: [], notables: "Same as IXS. Reference." },
  { iata: "NNY", icao: "VONN", name: "Neyveli Airport", city: "Neyveli", state: "Tamil Nadu", lat: 11.6114, lon: 79.5256, type: "domestic", passengers: 10000, cargo: 0, movements: 200, runways: 1, longestRunwayFt: 5000, elevationFt: 300, operator: "AAI", opened: 2024, airlines: ["Alliance Air"], topRoutes: ["MAA"], terminals: 1, parkingBays: 1, fuelType: "Jet A-1", avgDailyFlights: 1, internationalShare: 0, cargoShare: 0, hubFor: [], notables: "Lignite town. Newest TN airport. UDAN." },
  { iata: "ISK", icao: "VANS", name: "Nashik (Gandhinagar Ref)", city: "Nashik", state: "Maharashtra", lat: 19.9633, lon: 73.8073, type: "domestic", passengers: 100000, cargo: 0, movements: 1500, runways: 1, longestRunwayFt: 6500, elevationFt: 1900, operator: "AAI", opened: 2023, airlines: ["IndiGo"], topRoutes: ["BOM"], terminals: 1, parkingBays: 2, fuelType: "Jet A-1", avgDailyFlights: 2, internationalShare: 0, cargoShare: 0, hubFor: [], notables: "Same as ISK. New T1 2023." },
  { iata: "OMN", icao: "VAON", name: "Osmanabad Airport", city: "Osmanabad", state: "Maharashtra", lat: 18.248, lon: 76.058, type: "domestic", passengers: 10000, cargo: 0, movements: 300, runways: 1, longestRunwayFt: 6000, elevationFt: 2244, operator: "AAI", opened: 2023, airlines: ["IndiGo"], topRoutes: ["BOM"], terminals: 1, parkingBays: 2, fuelType: "Jet A-1", avgDailyFlights: 1, internationalShare: 0, cargoShare: 0, hubFor: [], notables: "Newest Maharashtra airport. UDAN." },
  { iata: "RTC", icao: "VARC", name: "Ratnagiri Airport", city: "Ratnagiri", state: "Maharashtra", lat: 17.0133, lon: 73.3277, type: "domestic", passengers: 10000, cargo: 0, movements: 300, runways: 1, longestRunwayFt: 5000, elevationFt: 240, operator: "AAI", opened: 2024, airlines: ["IndiGo"], topRoutes: ["BOM"], terminals: 1, parkingBays: 2, fuelType: "Jet A-1", avgDailyFlights: 1, internationalShare: 0, cargoShare: 0, hubFor: [], notables: "Konkan coast. Newest, opened 2024." },
  { iata: "LTU", icao: "VALT", name: "Latur Airport", city: "Latur", state: "Maharashtra", lat: 18.4111, lon: 76.4644, type: "domestic", passengers: 20000, cargo: 0, movements: 400, runways: 1, longestRunwayFt: 5000, elevationFt: 2139, operator: "AAI", opened: 2020, airlines: ["SpiceJet"], topRoutes: ["BOM", "HYD"], terminals: 1, parkingBays: 2, fuelType: "Jet A-1", avgDailyFlights: 1, internationalShare: 0, cargoShare: 0, hubFor: [], notables: "Marathwada region. UDAN." },
  { iata: "AKD", icao: "VAAK", name: "Akola Airport", city: "Akola", state: "Maharashtra", lat: 20.6989, lon: 77.0586, type: "domestic", passengers: 10000, cargo: 0, movements: 300, runways: 1, longestRunwayFt: 5000, elevationFt: 999, operator: "AAI", opened: 2021, airlines: ["SpiceJet"], topRoutes: ["BOM", "HYD"], terminals: 1, parkingBays: 2, fuelType: "Jet A-1", avgDailyFlights: 1, internationalShare: 0, cargoShare: 0, hubFor: [], notables: "Vidarbha region. Limited." },
  { iata: "SAG", icao: "VASG", name: "Sangli Airport", city: "Sangli", state: "Maharashtra", lat: 16.8605, lon: 74.5953, type: "domestic", passengers: 20000, cargo: 0, movements: 400, runways: 1, longestRunwayFt: 5000, elevationFt: 1820, operator: "AAI", opened: 2021, airlines: ["SpiceJet"], topRoutes: ["BOM", "BLR"], terminals: 1, parkingBays: 2, fuelType: "Jet A-1", avgDailyFlights: 1, internationalShare: 0, cargoShare: 0, hubFor: [], notables: "Sugar belt. Limited." },
  { iata: "NMI", icao: "VANM", name: "Navi Mumbai International Airport (NMIA)", city: "Navi Mumbai", state: "Maharashtra", lat: 18.9894, lon: 73.0642, type: "upcoming", passengers: 0, cargo: 0, movements: 0, runways: 2, longestRunwayFt: 13123, elevationFt: 25, operator: "Adani Group (NMIAL)", opened: 2025, airlines: [], topRoutes: [], terminals: 2, parkingBays: 0, fuelType: "Jet A-1", avgDailyFlights: 0, internationalShare: 0, cargoShare: 0, hubFor: [], notables: "Opening April 2025. Phase 1 capacity 20M pax. Final 90M." },
  { iata: "PNQ", icao: "VAPN", name: "Pune Purandar Airport (Upcoming)", city: "Pune", state: "Maharashtra", lat: 18.2, lon: 73.9, type: "upcoming", passengers: 0, cargo: 0, movements: 0, runways: 2, longestRunwayFt: 12000, elevationFt: 2000, operator: "AAI", opened: 2027, airlines: [], topRoutes: [], terminals: 1, parkingBays: 0, fuelType: "Jet A-1", avgDailyFlights: 0, internationalShare: 0, cargoShare: 0, hubFor: [], notables: "Under construction. Will replace Lohegaon." },
  { iata: "KGI", icao: "VIGI", name: "Jewar Airport (Noida International)", city: "Jewar", state: "Uttar Pradesh", lat: 28.167, lon: 77.5833, type: "upcoming", passengers: 0, cargo: 0, movements: 0, runways: 2, longestRunwayFt: 13123, elevationFt: 650, operator: "Yamuna International (Tata)", opened: 2025, airlines: [], topRoutes: [], terminals: 2, parkingBays: 0, fuelType: "Jet A-1", avgDailyFlights: 0, internationalShare: 0, cargoShare: 0, hubFor: [], notables: "Asia's largest upon completion. Phase 1 opens April 2025." },
  { iata: "KDH", icao: "OAKN", name: "Kargil Airport (Upcoming)", city: "Kargil", state: "Ladakh", lat: 34.5263, lon: 76.1548, type: "upcoming", passengers: 0, cargo: 0, movements: 0, runways: 1, longestRunwayFt: 6000, elevationFt: 8800, operator: "AAI", opened: 2025, airlines: [], topRoutes: [], terminals: 1, parkingBays: 2, fuelType: "Jet A-1", avgDailyFlights: 0, internationalShare: 0, cargoShare: 0, hubFor: [], notables: "Ladakh's 2nd airport. ALH ops planned." },
  { iata: "KZA", icao: "VAKZ", name: "Kaza Airport (Upcoming)", city: "Kaza", state: "Himachal Pradesh", lat: 32.2219, lon: 78.0697, type: "upcoming", passengers: 0, cargo: 0, movements: 0, runways: 1, longestRunwayFt: 4500, elevationFt: 12500, operator: "AAI", opened: 2027, airlines: [], topRoutes: [], terminals: 1, parkingBays: 2, fuelType: "Jet A-1", avgDailyFlights: 0, internationalShare: 0, cargoShare: 0, hubFor: [], notables: "Spiti Valley. World's highest airport." },
  { iata: "MUL", icao: "VAMU", name: "Mundra Airport (Private)", city: "Mundra", state: "Gujarat", lat: 22.8392, lon: 69.7219, type: "domestic", passengers: 0, cargo: 0, movements: 0, runways: 1, longestRunwayFt: 9500, elevationFt: 30, operator: "Adani Group (private)", opened: 2018, airlines: [], topRoutes: [], terminals: 0, parkingBays: 0, fuelType: "Jet A-1", avgDailyFlights: 0, internationalShare: 0, cargoShare: 0, hubFor: [], notables: "Private cargo. Adani's Mundra." },
  { iata: "YTL", icao: "VAYL", name: "Yavatmal Airport (Upcoming)", city: "Yavatmal", state: "Maharashtra", lat: 20.3933, lon: 78.0111, type: "upcoming", passengers: 0, cargo: 0, movements: 0, runways: 1, longestRunwayFt: 5000, elevationFt: 1083, operator: "AAI", opened: 2023, airlines: [], topRoutes: [], terminals: 1, parkingBays: 2, fuelType: "Jet A-1", avgDailyFlights: 0, internationalShare: 0, cargoShare: 0, hubFor: [], notables: "Upcoming UDAN. Opened 2023." },
  { iata: "CHG", icao: "VACH", name: "Chandrapur Airport (Upcoming)", city: "Chandrapur", state: "Maharashtra", lat: 19.995, lon: 79.2222, type: "upcoming", passengers: 0, cargo: 0, movements: 0, runways: 1, longestRunwayFt: 5000, elevationFt: 624, operator: "AAI", opened: 2024, airlines: [], topRoutes: [], terminals: 1, parkingBays: 2, fuelType: "Jet A-1", avgDailyFlights: 0, internationalShare: 0, cargoShare: 0, hubFor: [], notables: "Maharashtra newest. Opened 2024." },
  { iata: "CBR", icao: "VACB", name: "Chinyalisaur Airport (Upcoming)", city: "Chinyalisaur", state: "Uttarakhand", lat: 30.5833, lon: 78.3167, type: "upcoming", passengers: 0, cargo: 0, movements: 0, runways: 1, longestRunwayFt: 5000, elevationFt: 3000, operator: "AAI", opened: 2026, airlines: [], topRoutes: [], terminals: 1, parkingBays: 2, fuelType: "Jet A-1", avgDailyFlights: 0, internationalShare: 0, cargoShare: 0, hubFor: [], notables: "Garhwal. Upcoming." },
  { iata: "BEK", icao: "VABK", name: "Bhiwani Airport (Upcoming)", city: "Bhiwani", state: "Haryana", lat: 28.7833, lon: 76.1333, type: "upcoming", passengers: 0, cargo: 0, movements: 0, runways: 1, longestRunwayFt: 5000, elevationFt: 720, operator: "AAI", opened: 2026, airlines: [], topRoutes: [], terminals: 1, parkingBays: 2, fuelType: "Jet A-1", avgDailyFlights: 0, internationalShare: 0, cargoShare: 0, hubFor: [], notables: "Upcoming HR airport. UDAN." },
  { iata: "BDR", icao: "VABD", name: "Bidar Airport (Upcoming)", city: "Bidar", state: "Karnataka", lat: 17.9167, lon: 77.5167, type: "upcoming", passengers: 0, cargo: 0, movements: 0, runways: 1, longestRunwayFt: 5000, elevationFt: 1900, operator: "AAI", opened: 2027, airlines: [], topRoutes: [], terminals: 1, parkingBays: 2, fuelType: "Jet A-1", avgDailyFlights: 0, internationalShare: 0, cargoShare: 0, hubFor: [], notables: "Karnataka NE. Upcoming." },
  { iata: "HAS", icao: "VAHS", name: "Hassan Airport (Upcoming)", city: "Hassan", state: "Karnataka", lat: 13.0, lon: 76.1, type: "upcoming", passengers: 0, cargo: 0, movements: 0, runways: 1, longestRunwayFt: 5000, elevationFt: 2990, operator: "AAI", opened: 2027, airlines: [], topRoutes: [], terminals: 1, parkingBays: 2, fuelType: "Jet A-1", avgDailyFlights: 0, internationalShare: 0, cargoShare: 0, hubFor: [], notables: "Karnataka coffee region. Upcoming." },
  { iata: "RCH", icao: "VARC", name: "Raichur Airport (Upcoming)", city: "Raichur", state: "Karnataka", lat: 16.2, lon: 77.35, type: "upcoming", passengers: 0, cargo: 0, movements: 0, runways: 1, longestRunwayFt: 5000, elevationFt: 1280, operator: "AAI", opened: 2027, airlines: [], topRoutes: [], terminals: 1, parkingBays: 2, fuelType: "Jet A-1", avgDailyFlights: 0, internationalShare: 0, cargoShare: 0, hubFor: [], notables: "Karnataka. Upcoming." },
  { iata: "JLR", icao: "VAJB", name: "Bellary Airport (Upcoming)", city: "Bellary", state: "Karnataka", lat: 15.15, lon: 76.8333, type: "upcoming", passengers: 0, cargo: 0, movements: 0, runways: 1, longestRunwayFt: 5000, elevationFt: 1450, operator: "AAI", opened: 2026, airlines: [], topRoutes: [], terminals: 1, parkingBays: 2, fuelType: "Jet A-1", avgDailyFlights: 0, internationalShare: 0, cargoShare: 0, hubFor: [], notables: "Mining hub. Upcoming." },
  { iata: "BEY", icao: "VABY", name: "Beyt Dwarka Airport (Upcoming)", city: "Beyt Dwarka", state: "Gujarat", lat: 22.45, lon: 69.1333, type: "upcoming", passengers: 0, cargo: 0, movements: 0, runways: 1, longestRunwayFt: 4500, elevationFt: 20, operator: "AAI", opened: 2027, airlines: [], topRoutes: [], terminals: 1, parkingBays: 2, fuelType: "Jet A-1", avgDailyFlights: 0, internationalShare: 0, cargoShare: 0, hubFor: [], notables: "Gujarat coast. Upcoming." },
  { iata: "BMR", icao: "VABM", name: "Barmer Airport (Upcoming)", city: "Barmer", state: "Rajasthan", lat: 25.75, lon: 71.3833, type: "upcoming", passengers: 0, cargo: 0, movements: 0, runways: 1, longestRunwayFt: 5000, elevationFt: 500, operator: "AAI", opened: 2026, airlines: [], topRoutes: [], terminals: 1, parkingBays: 2, fuelType: "Jet A-1", avgDailyFlights: 0, internationalShare: 0, cargoShare: 0, hubFor: [], notables: "Rajasthan border. Upcoming." },
  { iata: "CDB", icao: "VECB", name: "Dhanbad Airport (Upcoming)", city: "Dhanbad", state: "Jharkhand", lat: 23.8333, lon: 86.45, type: "upcoming", passengers: 0, cargo: 0, movements: 0, runways: 1, longestRunwayFt: 5000, elevationFt: 850, operator: "AAI", opened: 2026, airlines: [], topRoutes: [], terminals: 1, parkingBays: 2, fuelType: "Jet A-1", avgDailyFlights: 0, internationalShare: 0, cargoShare: 0, hubFor: [], notables: "Coal capital. Upcoming." },
  { iata: "BOK", icao: "VABO", name: "Bokaro Airport (Upcoming)", city: "Bokaro", state: "Jharkhand", lat: 23.7833, lon: 85.8833, type: "upcoming", passengers: 0, cargo: 0, movements: 0, runways: 1, longestRunwayFt: 5000, elevationFt: 830, operator: "AAI", opened: 2027, airlines: [], topRoutes: [], terminals: 1, parkingBays: 2, fuelType: "Jet A-1", avgDailyFlights: 0, internationalShare: 0, cargoShare: 0, hubFor: [], notables: "Steel city. Upcoming." },
  { iata: "BPM", icao: "VABM", name: "Bhimavaram Airport (Upcoming)", city: "Bhimavaram", state: "Andhra Pradesh", lat: 16.5333, lon: 81.5167, type: "upcoming", passengers: 0, cargo: 0, movements: 0, runways: 1, longestRunwayFt: 5000, elevationFt: 50, operator: "AAI", opened: 2026, airlines: [], topRoutes: [], terminals: 1, parkingBays: 2, fuelType: "Jet A-1", avgDailyFlights: 0, internationalShare: 0, cargoShare: 0, hubFor: [], notables: "Coastal AP. Upcoming." },
  { iata: "ADB", icao: "VA1D", name: "Adilabad Airport (Upcoming)", city: "Adilabad", state: "Telangana", lat: 19.6667, lon: 78.5333, type: "upcoming", passengers: 0, cargo: 0, movements: 0, runways: 1, longestRunwayFt: 5000, elevationFt: 1010, operator: "AAI", opened: 2026, airlines: [], topRoutes: [], terminals: 1, parkingBays: 2, fuelType: "Jet A-1", avgDailyFlights: 0, internationalShare: 0, cargoShare: 0, hubFor: [], notables: "Telangana north. Upcoming." },
  { iata: "BHI", icao: "VABH", name: "Bhind Airport (Upcoming)", city: "Bhind", state: "Madhya Pradesh", lat: 26.5667, lon: 78.7833, type: "upcoming", passengers: 0, cargo: 0, movements: 0, runways: 1, longestRunwayFt: 5000, elevationFt: 580, operator: "AAI", opened: 2027, airlines: [], topRoutes: [], terminals: 1, parkingBays: 2, fuelType: "Jet A-1", avgDailyFlights: 0, internationalShare: 0, cargoShare: 0, hubFor: [], notables: "MP's upcoming. UDAN." },
  { iata: "CDR", icao: "VACD", name: "Chanderi Airport (Upcoming)", city: "Chanderi", state: "Madhya Pradesh", lat: 24.7167, lon: 78.1333, type: "upcoming", passengers: 0, cargo: 0, movements: 0, runways: 1, longestRunwayFt: 4500, elevationFt: 1430, operator: "AAI", opened: 2027, airlines: [], topRoutes: [], terminals: 1, parkingBays: 2, fuelType: "Jet A-1", avgDailyFlights: 0, internationalShare: 0, cargoShare: 0, hubFor: [], notables: "Heritage town. Upcoming." },
  { iata: "GUX", icao: "VAGU", name: "Guna Airport (Upcoming)", city: "Guna", state: "Madhya Pradesh", lat: 24.6547, lon: 77.3472, type: "upcoming", passengers: 0, cargo: 0, movements: 0, runways: 1, longestRunwayFt: 5000, elevationFt: 1600, operator: "AAI", opened: 2024, airlines: [], topRoutes: [], terminals: 1, parkingBays: 2, fuelType: "Jet A-1", avgDailyFlights: 0, internationalShare: 0, cargoShare: 0, hubFor: [], notables: "Newest MP. UDAN." },
  { iata: "PDB", icao: "VAPD", name: "Pithampur (Indore 2)", city: "Indore", state: "Madhya Pradesh", lat: 22.62, lon: 75.77, type: "upcoming", passengers: 0, cargo: 0, movements: 0, runways: 1, longestRunwayFt: 9000, elevationFt: 1850, operator: "AAI", opened: 2027, airlines: [], topRoutes: [], terminals: 1, parkingBays: 0, fuelType: "Jet A-1", avgDailyFlights: 0, internationalShare: 0, cargoShare: 0, hubFor: [], notables: "Indore 2nd airport. Planned." },
  { iata: "BSR", icao: "VABS", name: "Basna Airport (Upcoming)", city: "Basna", state: "Chhattisgarh", lat: 21.35, lon: 82.75, type: "upcoming", passengers: 0, cargo: 0, movements: 0, runways: 1, longestRunwayFt: 4500, elevationFt: 900, operator: "AAI", opened: 2027, airlines: [], topRoutes: [], terminals: 1, parkingBays: 2, fuelType: "Jet A-1", avgDailyFlights: 0, internationalShare: 0, cargoShare: 0, hubFor: [], notables: "CG's upcoming. UDAN." },
  { iata: "KBR", icao: "VAKB", name: "Korba Airport (Upcoming)", city: "Korba", state: "Chhattisgarh", lat: 22.35, lon: 82.6833, type: "upcoming", passengers: 0, cargo: 0, movements: 0, runways: 1, longestRunwayFt: 5000, elevationFt: 880, operator: "AAI", opened: 2026, airlines: [], topRoutes: [], terminals: 1, parkingBays: 2, fuelType: "Jet A-1", avgDailyFlights: 0, internationalShare: 0, cargoShare: 0, hubFor: [], notables: "Power hub. Upcoming." },
  { iata: "PNS", icao: "VAPN", name: "Purnia Airport (Upcoming)", city: "Purnia", state: "Bihar", lat: 25.7833, lon: 87.4667, type: "upcoming", passengers: 0, cargo: 0, movements: 0, runways: 1, longestRunwayFt: 5000, elevationFt: 200, operator: "AAI", opened: 2026, airlines: [], topRoutes: [], terminals: 1, parkingBays: 2, fuelType: "Jet A-1", avgDailyFlights: 0, internationalShare: 0, cargoShare: 0, hubFor: [], notables: "Bihar upcoming. UDAN." },
  { iata: "HRS", icao: "VAHR", name: "Harnaut Airport (Upcoming)", city: "Harnaut", state: "Bihar", lat: 25.3667, lon: 85.5333, type: "upcoming", passengers: 0, cargo: 0, movements: 0, runways: 1, longestRunwayFt: 5000, elevationFt: 170, operator: "AAI", opened: 2026, airlines: [], topRoutes: [], terminals: 1, parkingBays: 2, fuelType: "Jet A-1", avgDailyFlights: 0, internationalShare: 0, cargoShare: 0, hubFor: [], notables: "Bihar 2nd. Upcoming." },
  { iata: "BIR", icao: "VNBR", name: "Birgunj Airport (Closed)", city: "Birgunj", state: "Bihar", lat: 27.0667, lon: 84.8833, type: "domestic", passengers: 0, cargo: 0, movements: 0, runways: 1, longestRunwayFt: 5000, elevationFt: 300, operator: "AAI", opened: 1960, airlines: [], topRoutes: [], terminals: 1, parkingBays: 2, fuelType: "Jet A-1", avgDailyFlights: 0, internationalShare: 0, cargoShare: 0, hubFor: [], notables: "Closed. Nepal border town." },
  { iata: "BZU", icao: "VABU", name: "Basti Airport (Upcoming)", city: "Basti", state: "Uttar Pradesh", lat: 26.8, lon: 82.7167, type: "upcoming", passengers: 0, cargo: 0, movements: 0, runways: 1, longestRunwayFt: 4500, elevationFt: 280, operator: "AAI", opened: 2027, airlines: [], topRoutes: [], terminals: 1, parkingBays: 2, fuelType: "Jet A-1", avgDailyFlights: 0, internationalShare: 0, cargoShare: 0, hubFor: [], notables: "UP's upcoming. UDAN." },
  { iata: "AZR", icao: "VAAZ", name: "Azamgarh Airport (Upcoming)", city: "Azamgarh", state: "Uttar Pradesh", lat: 26.0667, lon: 83.1833, type: "upcoming", passengers: 0, cargo: 0, movements: 0, runways: 1, longestRunwayFt: 4500, elevationFt: 300, operator: "AAI", opened: 2027, airlines: [], topRoutes: [], terminals: 1, parkingBays: 2, fuelType: "Jet A-1", avgDailyFlights: 0, internationalShare: 0, cargoShare: 0, hubFor: [], notables: "UP Purvanchal. Upcoming." },
  { iata: "SAA", icao: "VASA", name: "Shravasti Airport (Upcoming)", city: "Shravasti", state: "Uttar Pradesh", lat: 27.5, lon: 82.05, type: "upcoming", passengers: 0, cargo: 0, movements: 0, runways: 1, longestRunwayFt: 4500, elevationFt: 380, operator: "AAI", opened: 2027, airlines: [], topRoutes: [], terminals: 1, parkingBays: 2, fuelType: "Jet A-1", avgDailyFlights: 0, internationalShare: 0, cargoShare: 0, hubFor: [], notables: "Buddhist site. Upcoming." },
  { iata: "BUI", icao: "VABU", name: "Budaun Airport (Upcoming)", city: "Budaun", state: "Uttar Pradesh", lat: 28.0333, lon: 79.1167, type: "upcoming", passengers: 0, cargo: 0, movements: 0, runways: 1, longestRunwayFt: 4500, elevationFt: 580, operator: "AAI", opened: 2027, airlines: [], topRoutes: [], terminals: 1, parkingBays: 2, fuelType: "Jet A-1", avgDailyFlights: 0, internationalShare: 0, cargoShare: 0, hubFor: [], notables: "UP's upcoming. UDAN." },
  { iata: "FBD", icao: "VAFB", name: "Farrukhabad Airport (Upcoming)", city: "Farrukhabad", state: "Uttar Pradesh", lat: 27.3833, lon: 79.5833, type: "upcoming", passengers: 0, cargo: 0, movements: 0, runways: 1, longestRunwayFt: 4500, elevationFt: 500, operator: "AAI", opened: 2027, airlines: [], topRoutes: [], terminals: 1, parkingBays: 2, fuelType: "Jet A-1", avgDailyFlights: 0, internationalShare: 0, cargoShare: 0, hubFor: [], notables: "UP's upcoming. UDAN." },
  { iata: "LDA", icao: "VILN", name: "Lalitpur Airport (Upcoming)", city: "Lalitpur", state: "Uttar Pradesh", lat: 24.6833, lon: 78.4167, type: "upcoming", passengers: 0, cargo: 0, movements: 0, runways: 1, longestRunwayFt: 5000, elevationFt: 1180, operator: "AAI", opened: 2027, airlines: [], topRoutes: [], terminals: 1, parkingBays: 2, fuelType: "Jet A-1", avgDailyFlights: 0, internationalShare: 0, cargoShare: 0, hubFor: [], notables: "UP Bundelkhand. Upcoming." },
  { iata: "SKP", icao: "VISK", name: "Sultanpur Airport (Upcoming)", city: "Sultanpur", state: "Uttar Pradesh", lat: 26.2667, lon: 82.1167, type: "upcoming", passengers: 0, cargo: 0, movements: 0, runways: 1, longestRunwayFt: 5000, elevationFt: 300, operator: "AAI", opened: 2026, airlines: [], topRoutes: [], terminals: 1, parkingBays: 2, fuelType: "Jet A-1", avgDailyFlights: 0, internationalShare: 0, cargoShare: 0, hubFor: [], notables: "Upcoming UP airport." },
  { iata: "SVD", icao: "VISV", name: "Saharanpur Airport (Upcoming)", city: "Saharanpur", state: "Uttar Pradesh", lat: 29.9667, lon: 77.55, type: "upcoming", passengers: 0, cargo: 0, movements: 0, runways: 1, longestRunwayFt: 5000, elevationFt: 880, operator: "AAI", opened: 2026, airlines: [], topRoutes: [], terminals: 1, parkingBays: 2, fuelType: "Jet A-1", avgDailyFlights: 0, internationalShare: 0, cargoShare: 0, hubFor: [], notables: "Upcoming UP airport." },
  { iata: "MRJ", icao: "VIMR", name: "Moradabad Airport (Upcoming)", city: "Moradabad", state: "Uttar Pradesh", lat: 28.8333, lon: 78.7667, type: "upcoming", passengers: 0, cargo: 0, movements: 0, runways: 1, longestRunwayFt: 5000, elevationFt: 660, operator: "AAI", opened: 2026, airlines: [], topRoutes: [], terminals: 1, parkingBays: 2, fuelType: "Jet A-1", avgDailyFlights: 0, internationalShare: 0, cargoShare: 0, hubFor: [], notables: "Brass city. UDAN." },
  { iata: "MNQ", icao: "VIMN", name: "Meerut Airport (Upcoming)", city: "Meerut", state: "Uttar Pradesh", lat: 28.9833, lon: 77.7333, type: "upcoming", passengers: 0, cargo: 0, movements: 0, runways: 1, longestRunwayFt: 5000, elevationFt: 700, operator: "AAI", opened: 2026, airlines: [], topRoutes: [], terminals: 1, parkingBays: 2, fuelType: "Jet A-1", avgDailyFlights: 0, internationalShare: 0, cargoShare: 0, hubFor: [], notables: "Upcoming UP airport. NCR 2nd tier." },
  { iata: "AIP", icao: "VA1P", name: "Aligarh Airport (Upcoming)", city: "Aligarh", state: "Uttar Pradesh", lat: 27.8833, lon: 78.0833, type: "upcoming", passengers: 0, cargo: 0, movements: 0, runways: 1, longestRunwayFt: 5000, elevationFt: 600, operator: "AAI", opened: 2026, airlines: [], topRoutes: [], terminals: 1, parkingBays: 2, fuelType: "Jet A-1", avgDailyFlights: 0, internationalShare: 0, cargoShare: 0, hubFor: [], notables: "Upcoming UP airport. UDAN." },
  { iata: "MUI", icao: "VEMR", name: "Muirpur Airport (Upcoming)", city: "Muirpur", state: "Uttar Pradesh", lat: 24.7667, lon: 83.15, type: "upcoming", passengers: 0, cargo: 0, movements: 0, runways: 1, longestRunwayFt: 6000, elevationFt: 1150, operator: "AAI", opened: 2027, airlines: [], topRoutes: [], terminals: 1, parkingBays: 2, fuelType: "Jet A-1", avgDailyFlights: 0, internationalShare: 0, cargoShare: 0, hubFor: [], notables: "Sonbhadra. Upcoming." },
  { iata: "MFT", icao: "VEMF", name: "Malda Airport (Upcoming)", city: "Malda", state: "West Bengal", lat: 25.0333, lon: 88.15, type: "upcoming", passengers: 0, cargo: 0, movements: 0, runways: 1, longestRunwayFt: 5000, elevationFt: 130, operator: "AAI", opened: 2026, airlines: [], topRoutes: [], terminals: 1, parkingBays: 2, fuelType: "Jet A-1", avgDailyFlights: 0, internationalShare: 0, cargoShare: 0, hubFor: [], notables: "WB upcoming. UDAN." },
  { iata: "REW", icao: "VARW", name: "Rewa Airport (Upcoming)", city: "Rewa", state: "Madhya Pradesh", lat: 24.5333, lon: 81.3, type: "upcoming", passengers: 0, cargo: 0, movements: 0, runways: 1, longestRunwayFt: 5000, elevationFt: 1040, operator: "AAI", opened: 2025, airlines: [], topRoutes: [], terminals: 1, parkingBays: 2, fuelType: "Jet A-1", avgDailyFlights: 0, internationalShare: 0, cargoShare: 0, hubFor: [], notables: "Upcoming MP airport. UDAN." },
  { iata: "PKR", icao: "VAPR", name: "Pithampur Airport (Upcoming)", city: "Indore", state: "Madhya Pradesh", lat: 22.62, lon: 75.77, type: "upcoming", passengers: 0, cargo: 0, movements: 0, runways: 1, longestRunwayFt: 9000, elevationFt: 1850, operator: "AAI", opened: 2027, airlines: [], topRoutes: [], terminals: 1, parkingBays: 0, fuelType: "Jet A-1", avgDailyFlights: 0, internationalShare: 0, cargoShare: 0, hubFor: [], notables: "Indore 2nd airport. Planned." },
  { iata: "CDP", icao: "VOND", name: "Karwar Airport (Upcoming)", city: "Karwar", state: "Karnataka", lat: 14.7667, lon: 74.1333, type: "upcoming", passengers: 0, cargo: 0, movements: 0, runways: 1, longestRunwayFt: 5000, elevationFt: 50, operator: "AAI", opened: 2027, airlines: [], topRoutes: [], terminals: 1, parkingBays: 2, fuelType: "Jet A-1", avgDailyFlights: 0, internationalShare: 0, cargoShare: 0, hubFor: [], notables: "Naval base. Upcoming." },
  { iata: "DIU", icao: "VADU", name: "Diu Airport", city: "Diu", state: "Dadra and Nagar Haveli and Daman and Diu", lat: 20.7131, lon: 70.9225, type: "domestic", passengers: 50000, cargo: 0, movements: 800, runways: 1, longestRunwayFt: 5000, elevationFt: 31, operator: "AAI", opened: 2000, airlines: ["SpiceJet"], topRoutes: ["BOM"], terminals: 1, parkingBays: 2, fuelType: "Jet A-1", avgDailyFlights: 2, internationalShare: 0, cargoShare: 0, hubFor: [], notables: "Island UT. UNESCO heritage Diu Fort." },
  { iata: "SRD", icao: "VASR", name: "Surendranagar Airport (Closed)", city: "Surendranagar", state: "Gujarat", lat: 22.7333, lon: 71.6333, type: "domestic", passengers: 0, cargo: 0, movements: 0, runways: 1, longestRunwayFt: 5000, elevationFt: 200, operator: "AAI", opened: 2000, airlines: [], topRoutes: [], terminals: 1, parkingBays: 2, fuelType: "Jet A-1", avgDailyFlights: 0, internationalShare: 0, cargoShare: 0, hubFor: [], notables: "Closed since 2010. Inactive." },

];

// === DEDUPLICATE BY IATA (keeps first occurrence) ===
export const FINAL_AIRPORTS = (() => {
  const seen = new Set<string>();
  const out: Airport[] = [];
  for (const a of ALL_AIRPORTS_RAW) {
    if (!seen.has(a.iata)) {
      seen.add(a.iata);
      out.push(a);
    }
  }
  return out;
})();

export const AIRPORT_STATS_FINAL = {
  totalAirports: FINAL_AIRPORTS.length,
  activeAirports: FINAL_AIRPORTS.filter((a) => a.passengers > 0).length,
  upcomingAirports: FINAL_AIRPORTS.filter((a) => a.type === "upcoming").length,
  totalPassengers: FINAL_AIRPORTS.reduce((s, a) => s + a.passengers, 0),
  totalCargo: FINAL_AIRPORTS.reduce((s, a) => s + a.cargo, 0),
  totalMovements: FINAL_AIRPORTS.reduce((s, a) => s + a.movements, 0),
  statesCovered: new Set(FINAL_AIRPORTS.map((a) => a.state)).size,
  totalRunways: FINAL_AIRPORTS.reduce((s, a) => s + a.runways, 0),
  avgDailyFlights: FINAL_AIRPORTS.reduce((s, a) => s + a.avgDailyFlights, 0),
};

// Backwards-compat exports
export const ALL_AIRPORTS = FINAL_AIRPORTS;
export const AIRPORT_STATS = AIRPORT_STATS_FINAL;
